### ISSUE TITLE
Arm.Neon missing  floating-point to (un)signed integer using "Round to Neareast" (vcvtnq_...)

### ISSUE THREAD

**Issue by jordy-van-appeven-accerion** [simd-everywhere/simde#1008]
Below a list of missing instructions:
- vcvtnq_s32_f32
- vcvtnq_s64_f64
- vcvtnq_u32_f32
- vcvtnq_u64_f64

**Comment by mr-c** [comment]
Hello @jordy-van-appeven-accerion ; I'll be merging https://github.com/simd-everywhere/simde/commit/fefc7857ff3e785b988a61a8f5f3c5bd5eb24342 later today. For which platforms, CPUs, and compilers are you targeting?

**Comment by mr-c** [comment]
@jordy-van-appeven-accerion You are welcome! 

How well do you know the SSE intrinsics? I made an attempt at an optimization for `vcvtnq_s32_f32` using SSE2 at https://github.com/simd-everywhere/simde/commit/0f4e25b4afec310249fe74d08a819cdb7fa733aa#diff-7d0724e45f5b51968d7a114163dc1ec5f2e755a4351bc5d6a520ab5631bdabd5R45 but I don't know how you are using this call, and if GCC will optimize recurrent usages to reduce the number of times the rounding mode register needs to be checked and set.
