### ISSUE TITLE
v0.7.4 does not install `neon/ld1.h`

### ISSUE THREAD

**Issue by p-linnane** [simd-everywhere/simde#1012]
Hello 👋 . I'm a maintainer for the [Homebrew](https://brew.sh) project. While packaging v0.7.4 of simde we are running into some issues with a missing header file. Running a simple test is failiing with:
```
  /home/linuxbrew/.linuxbrew/opt/simde/include/simde/arm/neon.h:84:10: fatal error: neon/ld1.h: No such file or directory
     84 | #include "neon/ld1.h"
        |          ^~~~~~~~~~~~
  compilation terminated.
```
The relevant GitHub Actions run can be found [here](https://github.com/Homebrew/homebrew-core/actions/runs/4896600056/jobs/8743721678?pr=130287).

Relates to https://github.com/Homebrew/homebrew-core/pull/130287

**Comment by mr-c** [comment]
Thanks @p-linnane ! Here's a patch: https://github.com/simd-everywhere/simde/commit/27836b19abf03886750a878fdacb1fcb7bcd9d85 ; you'll also want https://github.com/simd-everywhere/simde/commit/f9cf4675d101eef2dd70dabbb4d6806b405eac29

**Comment by p-linnane** [comment]
Confirming this fixed the issue for us. Thanks!
