### ISSUE TITLE
porting @Microsoft SPTAG (native aliases enabled) (continued): ): _mm512_madd_epi16 wrong args, __mmask64 typo, wrong definition, compile warnings

### ISSUE THREAD

**Issue by pabs3** [simd-everywhere/simde#1018]
@mr-c Thanks for the upload of 0.7.4 to Debian experimental and fixing #961 but unfortunately that wasn't quite enough for me to build SPTAG.

Firstly commit ae545ceb1c8abfb33b9f12b076aff18be9ec72a9 broke the definition of `_mm512_madd_epi16`, it mistakenly added two arguments to the start of the arguments, it should have two arguments not four, like the `simde_mm512_madd_epi16` function does. 

Secondly there was a typo in commit d850b8399ee8c592d454948e48f966eeb8a31c7b, `__mask64` should be `__mmask64` instead.

Thirdly the `typedef uint64_t __mmask64;` definition of `__mmask64` conflicts with the one in GCC from Debian bookworm, which defines it with `typedef unsigned long long __mmask64;` in `avx512bwintrin.h`.

Fourthly the code successfully compiled but with a couple of GCC warnings:

```
In file included from /usr/include/simde/x86/avx512/mov.h:32,
                 from /usr/include/simde/x86/avx512/dpwssd.h:5,
                 from /usr/include/simde/x86/avx512/4dpwssd.h:5,
                 from /usr/include/simde/x86/avx512.h:33,
                 from /home/pabs/sptag-test-simde/SPTAG.git/AnnService/inc/Core/Common/InstructionUtils.h:16,
                 from /home/pabs/sptag-test-simde/SPTAG.git/AnnService/inc/Core/Common/DistanceUtils.h:11,
                 from /home/pabs/sptag-test-simde/SPTAG.git/AnnService/src/Core/Common/DistanceUtils.cpp:4:
/usr/include/simde/x86/avx512/cast.h: In function 'simde__m512 simde_mm512_castsi512_ps(simde__m512i)':
/usr/include/simde/x86/avx512/cast.h:105:1: note: the ABI for passing parameters with 64-byte alignment has changed in GCC 4.6
  105 | simde_mm512_castsi512_ps (simde__m512i a) {
      | ^~~~~~~~~~~~~~~~~~~~~~~~
/home/pabs/sptag-test-simde/SPTAG.git/AnnService/src/Core/Common/DistanceUtils.cpp: In function 'simde__m512i simde_mm512_add_epi32(simde__m512i, simde__m512i)':
/home/pabs/sptag-test-simde/SPTAG.git/AnnService/src/Core/Common/DistanceUtils.cpp:1051:1: warning: AVX512F vector return without AVX512F enabled changes the ABI [-Wpsabi]
 1051 | }
      | ^
```

**Comment by pabs3** [comment]
Thanks. Before I was getting an error with `uint64_t` `__mmask64` but
just now I retried everything from scratch and didn't get any error. 

`SIMDE_DIAGNOSTIC_DISABLE_PSABI_` is automatically enabled for GCC
version 7 and above, since I'm using GCC 12, so it should be enabled
already but I am still seeing the two warnings.


-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by mr-c** [comment]
FYI: In https://github.com/simd-everywhere/simde/commit/e8390a3bfb3bd9e5119a9883fb29b07169b2fe4d I did add a `unsigned long long` variant for gcc.

> `SIMDE_DIAGNOSTIC_DISABLE_PSABI_` is automatically enabled for GCC version 7 and above, since I'm using GCC 12, so it should be enabled already but I am still seeing the two warnings.

Hmm.. I don't know what to say, sorry. Can you try adding `SIMDE_DIAGNOSTIC_DISABLE_PSABI_` to the SPTAG source files that generate warnings??

**Comment by pabs3** [comment]
I think the `unsigned long long __mmask64` is not actually needed, but
I guess it probably causes no harm anyway.

I forgot that the diagnostic disabling was only per source file.
Adding `SIMDE_DISABLE_UNWANTED_DIAGNOSTICS` after I include the simde
headers got rid of the warnings originating from those files, but there
is still the warning from `avx.h`, which already uses the macro and the
warning doesn't go away even when I add the macro just before the
function that causes the warning. For some reason none of the other
functions in the `avx.h` file generate the warning.

Anyway, if the warning issue isn't of concern to you, then you can
close this bug report now.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by mr-c** [comment]
Yeah, I think some of the fixes from `SIMDE_DISABLE_UNWANTED_DIAGNOSTICS` don't stick for `#define`d functions.

Thanks again for the feedback!
