### ISSUE TITLE
ARMv7 NEON is not tested

### ISSUE THREAD

**Issue by easyaspi314** [simd-everywhere/simde#1024]
There appear to be blatant compile errors on the ARMv7 polyfill, which are going unnoticed due to a lack of CI tests. Perhaps an `arm-linux-gnueabihf` CI test could be added? 

Note that some tests will not be detectable on QEMU due to NEON having some alignment-sensitive instructions and QEMU ignoring alignment checks. (see note in comment 1 on #1023)

Once CI tests are added, I will happily go through and fix the existing bugs.

**Comment by mr-c** [comment]
Hello @easyaspi314 ; yes, we used to test on real ARMv7 (and v8) with Drone.io; but that [configuration broke](https://github.com/simd-everywhere/simde/commit/fd10911c9aead1f39004e77a398c843011219cef) and I've been unable to find time to fix it. Adding a qemu test with cross compilation will be easier for me.

Or if you can get Drone.io working on your fork of SIMDe then I can look at enabling that again!

**Comment by mr-c** [comment]
Here's the first result: https://github.com/mr-c/simde/actions/runs/5036972757/jobs/9033504694#step:9:1067 from a test run using https://github.com/mr-c/simde/commit/168d4a8b78a3c2b8b78d74a92a993d432a92c50a
