### ISSUE TITLE
Adding Fedora rawhide case to the CI

### ISSUE THREAD

**Issue by junaruga** [simd-everywhere/simde#1036]
I finally have a spare time to work on Fedora rawhide case to this repository's CI that we discussed at <https://github.com/simd-everywhere/simde/issues/992#issuecomment-1528760367>.

## Motivation

The gcc and clang new versions are landing on Fedora rawhide earlier than other Linux distributions. And when I find the issues on the Fedora rawhide when working for the `simde` RPM package, the issues were not checked on this project's CI. It's effective when each pull-request can check by gcc and clang compiler on Fedora rawhide.

## How to implement

First, I investigate a way of using `Dockerfile` in the `docker/Dockerfile.fedora`.

One concern is that Fedora rawhide case was on Drone CI. But it was changed from Fedora rawhide to Fedora latest on the <https://github.com/simd-everywhere/simde/commit/76506b01324cc70fb654763908d50d2e3fcbebea>.

Then finally there is no Fedora case as Drone CI was removed by the commit <https://github.com/simd-everywhere/simde/commit/fd10911c9aead1f39004e77a398c843011219cef>. And right now there is no Fedora case?

So, how can I help you not to repeat this situation this time?

**Comment by mr-c** [comment]
Hey @junaruga 

Yeah, Drone.io stopped working for me. If you can get it working on your fork then I can add it back here.

Or you can propose using another CI provider; the choice is yours.

Thanks for volunteering to do this! We can add comments about keeping 'Rawhide' (that `Rawhide` is the latest development version of Fedora, not a named release that might go out of support later)

**Comment by junaruga** [comment]
Hi @mr-c

Sure. Let me check which CI is the best for the Fedora rawhide case first.

> Thanks for volunteering to do this! We can add comments about keeping 'Rawhide' (that Rawhide is the latest development version of Fedora, not a named release that might go out of support later)

OK. This is an important note for people who don't know what the Fedora rawhide is. I also keep in mind adding the note to the commit message.

**Comment by junaruga** [comment]
> Yeah, Drone.io stopped working for me.

Could you explain more about it? The CI jobs were not executed at the pull-request?

**Comment by mr-c** [comment]
> > Yeah, Drone.io stopped working for me.
> 
> Could you explain more about it? The CI jobs were not executed at the pull-request?
> 
> I am checking the Drone.io page. https://cloud.drone.io/simd-everywhere/simde

Correct, they just queued forever and then timed out.

**Comment by junaruga** [comment]
I am still working on it. I think the best choice is using [Packit CI](https://packit.dev/docs/guide/) that can directly connect to the Fedora project's native rawhide cases (x86_64, i686, aarch64 (arm64), ppc64le, s390x).

I succeeded to use it on my testing repository. (`job: copr_build`).

https://github.com/junaruga/ci-multi-arch-native-test/blob/2fbb07312282e50bffc887468eab37bf10ef0c34/.packit.yml#L39-L55

So, now I am trying to apply to SIMDe.

**Comment by mr-c** [comment]
@junaruga Great! I went ahead and installed their app on this repo, so once you figure out the basics we can add your `.packit.yml`

**Comment by junaruga** [comment]
Okay, thanks!

Note I am working on my forked repository's branch, <https://github.com/junaruga/simde/tree/wip/ci-packit>. And the issue https://github.com/packit/packit/issues/1992 is a blocker.

**Comment by mr-c** [comment]
> Okay, thanks!
> 
> Note I am working on my forked repository's branch, https://github.com/junaruga/simde/tree/wip/ci-packit. And the issue [packit/packit#1992](https://github.com/packit/packit/issues/1992) is a blocker.

We have this problem with the Debian package too. You might be able to skip the submodule. The default testing mode doesn't use munit. Or you could add it in via a patch, as q workaround. It hasn't changed in several releases.

**Comment by junaruga** [comment]
Thanks for telling info. I am going to go aheaed without munit. What is the merit of testing with munit comparing from the testing without munit?

**Comment by junaruga** [comment]
I sent the PR https://github.com/simd-everywhere/simde/pull/1041!
