### ISSUE TITLE
how to make sure that certain extensions are actually used

### ISSUE THREAD

**Issue by cbielow** [simd-everywhere/simde#1054]
is there a way to let SIMDe tell me what ISA extension it is currently targeting?

Depending on the platform, using SIMDe functions instead of the native ones, might deteriorate to something inferior, e.g. if I do not use `/arch=AVX` on MSVC, the I will get SSE2 instead of AVX since MSVC allows to use AVX instrinsics without any extra compiler flags. GCC/clang on Linux would error if I use native AVX intrinsics without the appropriate flag, but translating to SIMDe would use fallbacks.

So in any case, I need to be very careful with compile flags, to actually get the fast code I expect when using SIMDe functions.
Now, its kind of hard to check this for all platforms in CI (doing benchmarks on unknown hardware? Using a disassembler and inspect the output?

So finally the question: is there a function which reports the highest extension (or even all) which is currently used by SIMDe?
If not, can I rely on macros, e.g. [SIMDE_ARCH_ARM_NEON](https://github.com/simd-everywhere/simde/blob/master/simde/simde-arch.h#L121) as part of a stable"API" for SIMDe to write my own reporting class?

**Comment by cbielow** [comment]
So this is what I currently go with in OpenMS:
```
   #include <simde/simde-arch.h>
   ...
   std::vector<std::string> ret;

#ifdef SIMDE_ARCH_ARM_NEON
    ret.push_back("neon");
#endif
#ifdef SIMDE_ARCH_X86_SSE
    ret.push_back("SSE");
#endif
#ifdef SIMDE_ARCH_X86_SSE2
    ret.push_back("SSE2");
#endif
#ifdef SIMDE_ARCH_X86_SSE3
    ret.push_back("SSE3");
#endif
#ifdef SIMDE_ARCH_X86_SSE4_1
    ret.push_back("SSE4.1");
#endif
#ifdef SIMDE_ARCH_X86_SSE4_2
    ret.push_back("SSE4.2");
#endif
#ifdef SIMDE_ARCH_X86_AVX
    ret.push_back("AVX");
#endif
#ifdef SIMDE_ARCH_X86_AVX2
    ret.push_back("AVX2");
#endif
#ifdef SIMDE_ARCH_X86_FMA
    ret.push_back("FMA");
#endif
```

Can I assume this to stay stable?! I.e. SIMDe changes these defines, then our reporting will be false.

**Comment by mr-c** [comment]
Yes, those are stable and are enabled based upon the technology/arch level the compiler has chosen (in accordance with any flags or other user configuration)
