### ISSUE TITLE
intel intrinsics on (Aarch64/arm64/appleSilicon) _rdrand64_step ?

### ISSUE THREAD

**Issue by ouya99** [simd-everywhere/simde#1058]
RDRAND should be available on arm64 devices (such as apple silicon)

But yet "__ARM_FEATURE_RNG" is 0 on my m1 machine. 

Any idea how to use RDRAND or similar methods on m1 devices? is it part of a arm neon implementation?

Literature says armv8.5-a supports RDRAND. Doesn't arm-neon-compatible mean it should support it or does m1 not support armv85-a ?

Thank you for any link or idea

**Comment by ouya99** [comment]
just read that m1 is using Armv8.4-A A64 - since RDRAND is supported only in armv8.5, what else to choose from?

**Comment by mr-c** [comment]
For reference: https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#text=rdrand64_step&ig_expand=5344

Is https://developer.arm.com/documentation/ddi0601/2020-12/AArch64-Registers/RNDR--Random-Number available on M1?

**Comment by mr-c** [comment]
Worse case, maybe there is a libc function. Or directly read from `/dev/urandom`.

What application is using this intrinsic?

**Comment by ouya99** [comment]
its a windows application i would like to port to m1 

Could std::random_device be used? Seems gcc does use it.. on some machines

**Comment by mr-c** [comment]
> Could std::random_device be used? Seems gcc does use it.. on some machines

I think so. Likewise https://man7.org/linux/man-pages/man2/getrandom.2.html for Linux C users, and https://en.cppreference.com/w/c/numeric/random/rand for non-Linux C users.

I hope your application isn't doing cryptography, though!

**Comment by ouya99** [comment]
no cryptography, just need very random 32bit/64bit numbers. maybe i use boost lib for 64bit

so seems there is no such intrinsics for appleSilicon available , closing issue
