### ISSUE TITLE
VPCLMULQDQ should not be dectected if AVX512F is not present as well

### ISSUE THREAD

**Issue by Lithrein** [simd-everywhere/simde#1061]
The instruction VPCLMULQDQ is guarded both by `__VPCLMULQDQ__` and `__AVX512F__` as can be seen [here ](https://github.com/gcc-mirror/gcc/blob/master/gcc/config/i386/vpclmulqdqintrin.h) and which is confirmed on both gcc and clang as can be seen here ( 
https://godbolt.org/z/9YE1eEza4 ).

The detection in simde/simde-arch.h should take this into account.

**Comment by mr-c** [comment]
Hello @Lithrein and thanks for your report. Can you share some more context about how you came to this conclusion?

There is a `VPCLMULQDQ` intrinsic that doesn't require AVX512. Seems like AMD Zen 3 supports it: https://en.wikichip.org/wiki/x86/vpclmulqdq#Microarchitecture_support

https://en.wikipedia.org/wiki/AVX-512#VPCLMULQDQ

https://cdrdv2-public.intel.com/782158/325462-sdm-vol-1-2abcd-3abcd-4.pdf

Vol. 1 14-17
PROGRAMMING WITH INTEL® AVX, FMA, AND INTEL® AVX2
14.3.1 Detection of VEX-Encoded AES and VPCLMULQDQ

> the detection sequence for VPCLMULQDQ must combine checking for CPUID.1:ECX.PCLMULQDQ[bit 1] =
1 and the sequence for detection application support for Intel AVX.


VEX.256.66.0F3A.WIG 44 /r /ib
VPCLMULQDQ ymm1, ymm2, ymm3/m256, imm8
B
V/V
VPCLMULQDQ Carry-less multiplication of one quadword of ymm2 by one quadword of ymm3/m256, stores the 128-bit result in ymm1. The immediate is used to determine which quadwords of ymm2 and ymm3/m256 should be used

**Comment by Lithrein** [comment]
Hi @mr-c, thanks for your reply.

You are right, I was a bit hasty, and I was using an old version of SIMDe.

I came along this when investigating why `simde_mm512_clmulepi64_epi128` (the `VPCLMULQDQ` variant only available with `AVX512F`) failed on an AMD Zen 3.  This is because only the presence of `VPCLMULQDQ` was checked, but `VPCLMULQDQ` and `AVX512F` should have been checked. However, it appears that you fixed fixed this in commit 10a2f2869b6e648840ac6bdd5422f51349e0ecb8.

Thanks!
