### ISSUE TITLE
Error in implementation of simde_vmin_s16

### ISSUE THREAD

**Issue by M-HT** [simd-everywhere/simde#1063]
[This line](https://github.com/simd-everywhere/simde/blob/4d55fc25bcfddc0e2f0c744448557a070dd310c9/simde/arm/neon/min.h#L163C14-L163C14) (in function simde_vmin_s16) can't be compiled, because `_mm_subs_pu16` expects two input parameters and not one.

I'm not sure the specialization for `SIMDE_X86_MMX_NATIVE` should even be there, because there isn't such specialization in function `simde_vmax_s16`.

**Comment by rosbif** [comment]
Nice catch.

I think the intention in simde_vmin_s16 was to write:
      r_.m64 = _mm_sub_pi16(a_.m64, _mm_subs_pu16(a_.m64, b_.m64));
as in simde_vmin_u16.

I have difficulty getting my head around it but I don't think that this trick for u16 works for s16.

In any case it was obviously untested so I would remove this specialization.

**Comment by mr-c** [comment]
Thank you both, a PR to remedy this would be welcome

**Comment by M-HT** [comment]
Fixed in #1065
