### ISSUE TITLE
Wrong constant range in simde_vshll_n_XXX intrinsics

### ISSUE THREAD

**Issue by M-HT** [simd-everywhere/simde#1064]
In `simde_vshll_n_XXX` intrinsics the constant range is defined as 1-7 for 8-bit vectors, 1-15 for 16-bit vectors and 1-31 for 32-bit vectors (For example [here](https://github.com/simd-everywhere/simde/blob/4d55fc25bcfddc0e2f0c744448557a070dd310c9/simde/arm/neon/shll_n.h#L49C11-L49C11) for `simde_vshll_n_s8`).

These ranges are not correct because:
* In 32-bit arm, the  instruction `vshll` has two encodings. One encoding for shifts 1-7 for 8-bit vectors, 1-15 for 16-bit vectors and 1-31 for 32-bit vectors. And another encoding for shift 8 for 8-bit vectors, 16 for 16-bit vectors a 32 for 32-bit vectors.
* In 64-bit arm, there are instructions `sshll` and `ushll` which have shifts 0-7 for 8-bit vectors, 0-15 for 16-bit vectors and 0-31 for 32-bit vectors, and there's instruction `shll` which has shift 8 for 8-bit vectors, 16 for 16-bit vectors a 32 for 32-bit vectors.

Therefore the ranges in `simde_vshll_n_XXX` intrinsics should be extended at least to 1-8 for 8-bit vectors, 1-16 for 16-bit vectors a 1-32 for 32-bit vectors.

I'm not sure how zero shifts should be handled.

**Comment by rosbif** [comment]
I generally refer to the following document when writing NEON code: 
https://developer.arm.com/architectures/instruction-sets/intrinsics/#f:@navigationhierarchiessimdisa=[Neon]&q=vshll

From this document:
- It seems clear that shifts of 0 should be allowed.
- However I can see no mention of shifts of the element size in bits being allowed.
- I don't see any difference between A32 and A64.

Maybe you could change the minima from 1 to 0 and add test cases for these zero length shifts.

Remark:
My name appears in the copyright of shll.h but I am pretty sure that I didn't write it.
It probably started life as a copy of shl.h which I did write.

**Comment by M-HT** [comment]
About zero shifts on A32 - my documentation didn't mention it, but according to [this](https://developer.arm.com/documentation/100076/0200/a32-t32-instruction-set-reference/advanced-simd-instructions--32-bit-/vshll--by-immediate-?lang=en), zero shift is permitted, but resulting instruction is `vmovl`.

The page also mentions that shifts of the element size are allowed. Similarly for A64 [shll](https://developer.arm.com/documentation/ddi0596/2021-03/SIMD-FP-Instructions/SHLL--SHLL2--Shift-Left-Long--by-element-size--) instruction allows shifts of the element size. And from my testing, compilers support  shifts of the element size when using `vshll_n_XXX` intrinsics.

**Comment by M-HT** [comment]
I found [this documentation](https://arm-software.github.io/acle/neon_intrinsics/advsimd.html#vector-shift-left-and-widen) (which to me looks like official arm documentation) which describes intrinsics also for shifts of the element size.

**Comment by rosbif** [comment]
Oops, sorry: you seem to be right.
I knew about the right shifts which go from one to the element size, but I have never seen these left shifts of the element size in the document I quoted. I must look again.
Apparently instead of generating `SSHLL` or `USHLL` instructions, they generate `SHLL` instructions.

So it looks as if the range should be zero to the element size in bits, and test code must be added for both extremes.

**Comment by rosbif** [comment]
After a search it seems that in the document I cited, a description and pseudo-code corresponding to `vshll_n_u16` with n=16 appears but under the incorrect title of `vcvt_f32_bf16` (and also under `vcvtq_low_f32_bf16`).

(There is also the assembly code corresponding to `vshll_high_n_u16` with n=16 under the title `vcvtq_high_f32_bf16`.)

This is not the first time that I have found intrinsics in this document with totally incorrect descriptions and pseudo-code.
It looks as if someone started to add these cases but never finished the job, leaving copy/paste errors .

**Comment by M-HT** [comment]
Actually, `vcvt_f32_bf16`, `vcvtq_low_f32_bf16`, `vcvtq_high_f32_bf16` are not incorrect, because [bfloat16](https://en.wikipedia.org/wiki/Bfloat16_floating-point_format) numbers are the upper 16-bits of 32-bit floating point numbers. Converting bfloat16 to 32-bit floating point means extending from 16-bits to 32-bits and shifting left by 16, which is what `shll` instruction does.

**Comment by mr-c** [comment]
Can someone summarize this for me or open a PR? I'd like to make a new SIMDe release in the next week..

**Comment by M-HT** [comment]
Fixed in #1068
