### ISSUE TITLE
Problem detecting the lack of _Float16 on Clang-Cl with /arch:SSE (x86)

### ISSUE THREAD

**Issue by Epixu** [simd-everywhere/simde#1069]
The following cmake settings for a 32bit build with clang-cl, with only SSE enabled:
`-G "Visual Studio 17 2022" -A Win32 -T "ClangCl" -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="/arch:SSE"`
(Clang 16.0.5 with MSVC-like command-line)
Caused error:
`simde-f16.h(94,11): error : _Float16 is not supported`

Seems like detection in `simde-f16.h` is generally sketchy, additionally because detecting clang-cl involves checking for both `__clang__` and `_MSC_VER` at the same time. 
I was able to circumvent the issue by detecting _Float16 availablity like this:
```c++
// Make sure _Float16 identifier exists in such cases, and if not,   
// use the portable alternative provided by SIMDe                       
// Do this before including any SIMDe headers
#ifdef __is_identifier
  #if !__is_identifier(_Float16)
    #define SIMDE_FLOAT16_API 1     // SIMDE_FLOAT16_API_PORTABLE == 1  
  #endif
#endif
```

I saw a comment, that you're searching for suggestions on more robust detection of `_Float16`, so I thought this will be helpful. I could probably do a PR at some point, but I'm quite busy atm.

**Comment by mr-c** [comment]
Thank you @Epixu for your report. Yes, I would welcome a PR from you (or anyone else) to fix this.

**Comment by mr-c** [comment]
@Epixu I've implemented your suggestion at https://github.com/simd-everywhere/simde/commit/65efab3c8c4418f977e64c7b78ec9ad30922c62c but when testing x86 with MSVC I'm getting several errors. Do you think you can help fix those? https://ci.appveyor.com/project/nemequ/simde/builds/48302991

Then I'll add ClangCI + x86 to the CI and we can tackle anything else that comes up

**Comment by mr-c** [comment]
@Epixu can you test https://github.com/simd-everywhere/simde/commit/e75e82ebec06b66e1243abd21b4506148911d19c  using a 32-bit `Clang-Cl` build?

**Comment by Epixu** [comment]
@mr-c I will check it by the end of the work week

**Comment by Epixu** [comment]
@mr-c  [Here's how my CI responds to your commit](https://github.com/Langulus/SIMD/actions/runs/6667968209/job/18122509653)
Currently the G++ build fails. The problem appears to be due to `__is_identifier` not being handled by the preprocessor, but by the compiler, so it has to be encapsulated in the `#ifdef __is_identifier ... #endif` scope in order to work. 
I'll wait for the CI to finish and make additional comments later today, or tomorrow

**Comment by Epixu** [comment]
PS: The same problem appears to be affecting the Clang-Cl/MSVC builds

**Comment by mr-c** [comment]
In your original post you say that your setup doesn't allow for `__Float16` but the SIMDe code was detecting it as supported.

So to fix the logic, I need statements to skip your configuration at 

https://github.com/simd-everywhere/simde/blob/f132275f85ab1c1cb1e890538ee552c11ca09c38/simde/simde-f16.h#L68-L79

So it can eventually fall through to a more appropriate selection (Either `SIMDE_FLOAT16_API_FP16_NO_ABI` or `SIMDE_FLOAT16_API_PORTABLE` since you are on x86, but also using Clang)

@Epixu 

1. Does https://github.com/simd-everywhere/simde/commit/c98b76a0a6a3708ae56d85b863583d8d77c4ff7b work for your setup?

3. Can you suggest changes to https://github.com/simd-everywhere/simde/blob/master/.appveyor.yml so we can test Clang-Cl ourselves?

**Comment by Epixu** [comment]
Honestly, I'm so pissed with Clang-Cl at this point, that I'm at the precipice of ditching it entirely, because it has been causing me endless headaches from day one...

**Comment by mr-c** [comment]
@Epixu sorry to hear that; let me know if it turns out that https://github.com/simd-everywhere/simde/commit/c98b76a0a6a3708ae56d85b863583d8d77c4ff7b fixes your issue

``` diff
diff --git a/simde/simde-f16.h b/simde/simde-f16.h
index 4024dd18f..da14c68cd 100644
--- a/simde/simde-f16.h
+++ b/simde/simde-f16.h
@@ -66,6 +66,7 @@ SIMDE_BEGIN_DECLS_
  * welcome. */
 #if !defined(SIMDE_FLOAT16_API)
   #if !defined(__EMSCRIPTEN__) && !(defined(__clang__) && defined(SIMDE_ARCH_POWER)) && \
+    !(defined(HEDLEY_MSVC_VERSION) && defined(__clang__)) && \
     !(defined(__clang__) && defined(SIMDE_ARCH_RISCV64)) && ( \
       defined(SIMDE_X86_AVX512FP16_NATIVE) || \
       (defined(SIMDE_ARCH_X86_SSE2) && HEDLEY_GCC_VERSION_CHECK(12,0,0)) || \
```

**Comment by Epixu** [comment]
The commit you proposed [fails for x86 windows v143/clang-cl entirely](https://github.com/Langulus/SIMD/actions/runs/6772751881/job/18406065717), but as I mentioned previously, it fails likely due to completely unrelated reasons in svml.h

I will check if that particular change you made solves the issue for the stable version of SIMDe that I'm using, so that you can eventually closet his particular issue

**Comment by mr-c** [comment]
Oh, SVML; I bet Clang-Cl doesn't implement that; we had recently turned that on for MSVC 2019+ in 593af95cd9f43a96f66a582a9ae32dfe5dfd8eaa

If you want to try again with latest SIMDe, I've added https://github.com/simd-everywhere/simde/commit/ec6811e0f49df445d2f9ce04823b01ea079cf8ca to https://github.com/simd-everywhere/simde/compare/ci/appveyor/Win32

**Comment by Epixu** [comment]
I can confirm, that c98b76a fixes the problem I had, when applied to 4d55fc25bcfddc0e2f0c744448557a070dd310c9

I will now test the new commit you proposed, regarding SVML, but I think it is fine to close this issue

**Comment by mr-c** [comment]
Thanks for the testing, @Epixu !

**Comment by Epixu** [comment]
@mr-c ec6811e0f49df445d2f9ce04823b01ea079cf8ca
[does fix the issues with SVML partially](https://github.com/Langulus/SIMD/actions/runs/6773280806/job/18407792932)
MSVC v143 in x86 is till failing, though.
(Just curious, if you're able to see the build logs from my links or not, I'm not completely aware of github's behavior)

On a sidenote about any suggestions regarding .appveyor - I'm completely unaware how these scripts work at this point. If [my scripts](https://github.com/Langulus/SIMD/blob/main/.github/workflows/ci.yml) are somehow of help, please feel free to use them

**Comment by mr-c** [comment]
Thanks for the update! I bet some MMX is being used on our side which has too much precision as compared to IEEE floats

I'm now sold on @easyaspi314 's proposal to remove MMX using implementations from SIMDe https://github.com/simd-everywhere/simde/issues/1025
