### ISSUE TITLE
redhat gcc 14 ICE on i386

### ISSUE THREAD

**Issue by mr-c** [simd-everywhere/simde#1128]
```
FAILED: test/arm/neon/ext-native-c.p/ext.c.o 
gcc -Itest/arm/neon/ext-native-c.p -Itest/arm/neon -I../../test/arm/neon -I. -I../.. -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c99 -g -O2 -fopenmp-simd -DSIMDE_CONSTRAINED_COMPILATION -DSIMDE_ENABLE_OPENMP -Wno-psabi -DSIMDE_TEST_BARE -ffloat-store -MD -MQ test/arm/neon/ext-native-c.p/ext.c.o -MF test/arm/neon/ext-native-c.p/ext.c.o.d -o test/arm/neon/ext-native-c.p/ext.c.o -c ../../test/arm/neon/ext.c
during GIMPLE pass: local-fnsummary
../../test/arm/neon/ext.c: In function â€˜simde_vext_p64â€™:
../../test/arm/neon/ext.c:2236: internal compiler error: in predicate_for_phi_result, at ipa-fnsummary.cc:2445
Please submit a full bug report, with preprocessed source (by using -freport-bug).
See <http://bugzilla.redhat.com/bugzilla> for instructions.
Preprocessed source stored into /tmp/cchL3c7C.out file, please attach this to your bugreport.
```
https://download.copr.fedorainfracloud.org/results/packit/simd-everywhere-simde-1127/fedora-rawhide-i386/06994644-simde/builder-live.log.gz
https://download.copr.fedorainfracloud.org/results/packit/simd-everywhere-simde-1127/fedora-rawhide-i386/06994644-simde/
https://dashboard.packit.dev/results/copr-builds/1313878

@junaruga can you file the bug with RedHat?

Also, on s390x we get new test failures:
```
17:55:09 /builddir/build/BUILD/simde-v0.8.0.rc1/build/gcc-O2/test/arm/neon/addv-native-c
not ok 8 addv/vaddvq_f32
../../test/arm/neon/addv.c:357: assertion failed: r ~= test_vec[i].r (0.000000 ~= -1780.969971)
```
(same for the neon/addv emul and C++ variants)
https://download.copr.fedorainfracloud.org/results/packit/simd-everywhere-simde-1127/fedora-rawhide-s390x/06994644-simde/builder-live.log.gz

**Comment by junaruga** [comment]
Do you know which commit in this repository triggered the failure? Or a new version gcc 14 on Fedora rawhide triggered the failure? If you think it is a bug of the gcc14, one possible way to report the issue to [the upstream GCC project](https://gcc.gnu.org/bugs/).

You know the detail of the bug. You can create an account, and [report the issue with selecting component: gcc on Bugzilla](https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora).

**Comment by junaruga** [comment]
Sorry, I am negative the issue to the Fedora project by myself.

**Comment by junaruga** [comment]
If you want to reproduce the issue on Fedora rawhide on your local, below are the container images.

* https://quay.io/repository/fedora/fedora
* https://hub.docker.com/_/fedora/

**Comment by mr-c** [comment]
@junaruga Yeah, we don't do any gcc 14 testing yet besides via your Fedora CI setup; it would be a big help if you had the time to file GCC bugs for us

**Comment by Artoria2e5** [comment]
Likely unrelated, but your environment has an encoding issue: `â€˜simde_vext_p64â€™` indicates that you have UTF-8 output from gcc (presumably a remote machine with `LC_ALL=something.UTF-8`), but your terminal program is decoding it as either Latin-1 or Windows-1252. You might want to get that fixed.

**Comment by sharkcz** [comment]
a couple notes
- if access to a s390x machine would help, please let me know
- because I am not familiar with simde at all, is there a way to run the single failing test so I can take a closer look?

**Comment by mr-c** [comment]
> * because I am not familiar with simde at all, is there a way to run the single failing test so I can take a closer look?

Thank you for asking, I've added some documentation about this https://github.com/simd-everywhere/simde/pull/1140/files?short_path=eca12c0#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055 ; please leave a comment there with any feedback you have.

So for the s390x test mentioned above:

```
meson test --print-errorlogs arm/neon/addv-native-c
```

or 

```
meson test --print-errorlogs arm/neon/addv-{emul,native}-{c,cpp}
```
for all the variations.

**Comment by sharkcz** [comment]
for the record, we have now https://bugzilla.redhat.com/show_bug.cgi?id=2265489 and https://gcc.gnu.org/bugzilla/show_bug.cgi?id=114075 for the s390x test failures (miscompilations) with gcc 14

**Comment by mr-c** [comment]
Thank you @sharkcz !! Can you add those bugs to our tracking table at https://github.com/simd-everywhere/simde/wiki/Compiler-Bugs ?

**Comment by sharkcz** [comment]
for the record, https://gcc.gnu.org/bugzilla/show_bug.cgi?id=114075 was fixed a while ago

**Comment by mr-c** [comment]
Thank you @sharkcz ; I am seeing that at https://copr.fedorainfracloud.org/coprs/packit/simd-everywhere-simde-1154/build/7211582/

Can you help us by filing the bug for i386?

**Comment by sharkcz** [comment]
I am going to leave it to @junaruga , he is the simde maintainer in Fedora and my focus is on ppc64le and s390x. It shouldn't be difficult though, as it's an ICE.

**Comment by junaruga** [comment]
Seeing the copr build page, I see the latest GCC 14.0.1-0.12.fc41 is used. As I don't see the i686 failure for [the build with simde version 0.7.6 on the rawhide](https://bugzilla.redhat.com/show_bug.cgi?id=2261693#c9), the issue may be this repository's master branch or newer versions specific.

I hope we drop the Packit CI's i686 (i386) case on this repository. I don't think that I want to spend time to work for the i686 any more. Then I will drop the i686 support in simde RPM package on Fedora too. Below are the situation around the i686 (i386) on Fedora project. 

* https://fedoraproject.org/wiki/Changes/EncourageI686LeafRemoval
* https://fedoramagazine.org/in-fedora-31-32-bit-i686-is-86ed/

**Comment by junaruga** [comment]
> I hope we drop the Packit CI's i686 (i386) case on this repository. I don't think that I want to spend time to work for the i686 any more. Then I will drop the i686 support in simde RPM package on Fedora too. Below are the situation around the i686 (i386) on Fedora project.

I sent the PR to drop the i386 (i686) case on Packit CI now.
https://github.com/simd-everywhere/simde/pull/1155

**Comment by mr-c** [comment]
Thank you @junaruga !
