### ISSUE TITLE
Significant performance issue with simde_mm256_round_ps

### ISSUE THREAD

**Issue by Remnant44** [simd-everywhere/simde#1219]
Hi there,

I've run into fairly severe performance issues using SIMDE AVX intrinsics when targeting SSE on MSVC. The current issue being raised here is from code that uses simde_mm256_floor_ps() (which calls simde_mm256_round_ps) inside of the innermost loop.

My expectation would be that simde_mm256_round_ps would crack the 256bit value into two 128bit halves and send each to simde_mm_round_ps. When targeting SSE 4.1, this would then produce efficient single-op code on 128bit halves.

And it appears when SSE4.1 is defined on Clang/GCC, this is what happens. MSVC does not do well however.

Here is a link showing lousy codegen on MSVC:

https://godbolt.org/z/6Ezqrj56s

Although MSVC appears to autovectorize this, it does so with significant overhead compared to the expected two-instruction result, which trashes the inner loop performance my code counts on.

The major cause appears to be : 

1) The expected performant fallback code within simde__mm256_round_ps is gated by a "defined(SIMDE_STATEMENT_EXPR_)", which does not appear to get defined on MSVC? To be honest I'm not fully up to speed on the preprocessor machinery used within SIMDe and the operation of the statement expression components above. It appears to be a way to work around for the fact that the native intrinsic only accepts a constexpr expression. I'm a C++ guy, I'm used to templates for this kind of thing ;)

2) MSVC provides no way to specify SSE 4.1 instead of SSE2 baseline, which means that simde_mm_round_ps would be severely pessimized even if it got called ;) This can be worked around by forcing the SSE arch with a define however.

I will be fixing this for my own purposes, and I'd like to do so in a way that would allow the work to be contributed back, which means figuring out the preprocessor machinery here and why its not enabled for MSVC. Any help would be appreciated!

**Comment by mr-c** [comment]
> 1. The expected performant fallback code within simde__mm256_round_ps is gated by a "defined(SIMDE_STATEMENT_EXPR_)", which does not appear to get defined on MSVC?

Yeah, the challenge with the `simde_mm_round_ps` is that it has a `const` parameter, so we can't call it from another function using a non-`const` value.

Almost all compiler allow us to `#define` an expression using the `(__extension__ …)` syntax, except for MSVC

https://github.com/simd-everywhere/simde/blob/99ac62baab846bf26908e8ab22ba4a9036b90a9c/simde/simde-common.h#L202-L212

Perhaps there could be a workaround using the `SIMDE_CONSTIFY_16_`  from [`simde/simde-constify.h`](https://github.com/simd-everywhere/simde/blob/master/simde/simde-constify.h) ?
