### ISSUE TITLE
AVX512F: _mm512_fmaddsub_pd is missing

### ISSUE THREAD

**Issue by robinchrist** [simd-everywhere/simde#1243]
It seem like the AVX512F `_mm512_fmaddsub_pd` intrinsic is missing.

Could it please be added? :)

**Comment by mr-c** [comment]
Hello @robinchrist ; I would accept a PR to add a `simde_mm512_fmaddsub_pd` in a new file named `simde/x86/avx512/fmaddsub.h` ; I can assist you in that if you would like. Take a look at the following:

- https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#text=_mm512_fmaddsub_pd&ig_expand=3171
- [`simde_mm_fmaddsub_pd`](https://github.com/simd-everywhere/simde/blob/fa6a8690b84e242c6be426522c8ce282ca33fa2b/simde/x86/fma.h#L182-L194)
- [`simde_mm256_fmaddsub_pd`](https://github.com/simd-everywhere/simde/blob/fa6a8690b84e242c6be426522c8ce282ca33fa2b/simde/x86/fma.h#L196-L208)

**Comment by robinchrist** [comment]
@mr-c yeah this is way too complicated for me, honestly

The complexity lies in the addsub, e.g. https://github.com/simd-everywhere/simde/blob/fa6a8690b84e242c6be426522c8ce282ca33fa2b/simde/x86/avx.h#L1734-L1767

I can TRY, but don't expect a great solution. Especially not something that has LoongArch or NEON in it

**Comment by robinchrist** [comment]
Would you want the non-fma addsub in a separate file? Or in the same file as `simde_mm512_fmaddsub_pd`?

**Comment by robinchrist** [comment]
Hm, interesting. A `_mm512_addsub_pd` does not exist.
Should `_mm512_addsub_pd` be added nevertheless, or only with with the `simde_` prefix?
Or should I simply embed the functionality of `_mm512_addsub_pd` in `_mm512_fmaddsub_pd` and not offer it separately?

**Comment by mr-c** [comment]
> I can TRY, but don't expect a great solution. Especially not something that has LoongArch or NEON in it

We only need a plain implementation to merge; no `SIMDE_*_NATIVE` code needed. Others will come along with optimized implementations later. Often the compilers do a great job!

> Hm, interesting. A `_mm512_addsub_pd` does not exist. Should `_mm512_addsub_pd` be added nevertheless, or only with with the `simde_` prefix? Or should I simply embed the functionality of `_mm512_addsub_pd` in `_mm512_fmaddsub_pd` and not offer it separately?

Your choice.  If you need it, then call it `simde_x_mm512_addsub_pd`, and it can go in the same file.

**Comment by robinchrist** [comment]
I've made a first PR https://github.com/simd-everywhere/simde/pull/1246, no clue whether this works yet (tests should / will follow).
Can you please let me know in the PR whether this goes into the desired direction?

**Comment by mr-c** [comment]
Fixed in #1246 ; thank you!
