### ISSUE TITLE
Support __builtin_shufflevector and convertvector where appropriate

### ISSUE THREAD

**Issue by nemequ** [simd-everywhere/simde#13]
They're clang-specific, but clang uses them to implement a lot of the shuffle/convert intrinsics instead of calling an intrinsic specifically for the underlying instruction like GCC does, which means it should be a very fast abstraction we could use for non-native implementations instead of relying on the portable versions.

This should be pretty straightforward, and a big performance win, so it will probably be my priority after SSE2 is finished.

**Comment by nemequ** [comment]
There may still be some places where they could be used, but for the most part this is done.

If anyone notices somewhere we could/should be using one of these please file an issue.

**Comment by kapsyst** [comment]
Hi @nemequ, when I try and use `SIMDE_MM_SHUFFLE` within a loop using the index as input I get:
```
index for __builtin_ shuffle vector must be a constant integer
```
Is there a way around this?
