### ISSUE TITLE
AVX-512 VBMI functions

### ISSUE THREAD

**Issue by nemequ** [simd-everywhere/simde#221]
https://software.intel.com/sites/landingpage/IntrinsicsGuide/#avx512techs=AVX512_VBMI

For progress, see https://github.com/simd-everywhere/implementation-status/blob/main/x86.md#avx512_vbmi

**Comment by mr-c** [comment]
These are done! https://github.com/simd-everywhere/implementation-status/blob/main/x86.md#avx512_vbmi
