### ISSUE TITLE
AVX-512 VP2INTERSECT functions

### ISSUE THREAD

**Issue by nemequ** [simd-everywhere/simde#224]
https://software.intel.com/sites/landingpage/IntrinsicsGuide/#avx512techs=AVX512_VP2INTERSECT

Also requires AVX512F:

 - [x] _mm512_2intersect_epi32
 - [x] _mm512_2intersect_epi64

Also requires AVX512VL:

 - [x] _mm_2intersect_epi32
 - [x] _mm_2intersect_epi64
 - [x] _mm256_2intersect_epi32
 - [x] _mm256_2intersect_epi64

**Comment by ashnewmanjones** [comment]
I have implemented these here: https://github.com/ashnewmanjones/simde/commits/avx512vp2intersect.

I will send a PR once I have finished the tests.
