### ISSUE TITLE
Add range and constant requirement information to all functions which take a const or imm8

### ISSUE THREAD

**Issue by nemequ** [simd-everywhere/simde#267]
There are a lot of functions in the Intel APIs which are supposed to require that an argument is a compile-time constant (some compilers actually require integer constant expressions).  There are also a lot of functions which require that inputs be in a specific range.

Unfortunately, the Intrinsics Guide can't be trusted.  In *lots* of places it says an argument should be an 8-bit immediate-mode constant; sometimes they do this by calling the argument "imm8".  Sometimes it's a `const int` instead of just an `int`.  Sometimes the description just mentions that something is a immediate mode constant and there are no other indications (though for this issue we can ignore those).

Even when the IIG annotates something as immediate mode, sometimes compilers are okay with you using non-constant values and they'll just generate slightly different code (usually a (v)movd and the instruction instead of just the instruction with an immediate-mode value.

Additionally, sometimes the IIG can't be trusted about valid ranges, either.  There will often be pseudo-code which uses `imm8[7:0]` (implying that all 8 bits are used), but in reality only a few bits are used and/or compilers will generate an error because the input is out of range.

I'd like to use the `SIMDE_REQUIRE_CONSTANT_RANGE` and `SIMDE_REQUIRE_RANGE` macros to document all this, but unfortunately it will require going through the functions manually to see how different compilers handle different cases.  It's not particularly difficult, but it's definitely going to take a lot of time.  [Using Compiler Explorer](https://godbolt.org/z/DnL_x9) should help significantly.

A bunch of functions in SIMDe are already annotated with `SIMDE_REQUIRE_RANGE`; for those only the constant requirements need to be checked and, if a constant is required, altered to use `SIMDE_REQUIRE_CONSTANT_RANGE`.

List of functions with imm8 parameters from SSE thru AVX2 and FMA:

 * [x] _mm_extract_pi16
 * [x] _m_pextrw
 * [x] _mm_insert_pi16
 * [x] _m_pinsrw
 * [x] _mm_shuffle_pi16
 * [x] _m_pshufw
 * [x] _mm_shuffle_ps
 * [x] _mm_slli_si128
 * [x] _mm_bslli_si128
 * [x] _mm_bsrli_si128
 * [ ] _mm_slli_epi16
 * [ ] _mm_slli_epi32
 * [ ] _mm_slli_epi64
 * [ ] _mm_srai_epi16
 * [ ] _mm_srai_epi32
 * [ ] _mm_srli_si128
 * [ ] _mm_srli_epi16
 * [ ] _mm_srli_epi32
 * [ ] _mm_srli_epi64
 * [ ] _mm_extract_epi16
 * [ ] _mm_insert_epi16
 * [ ] _mm_shuffle_epi32
 * [ ] _mm_shufflehi_epi16
 * [ ] _mm_shufflelo_epi16
 * [ ] _mm_shuffle_pd
 * [ ] _mm_alignr_epi8
 * [ ] _mm_alignr_pi8
 * [ ] _mm_blend_pd
 * [ ] _mm_blend_ps
 * [ ] _mm_blend_epi16
 * [ ] _mm_dp_pd
 * [ ] _mm_dp_ps
 * [ ] _mm_extract_ps
 * [ ] _mm_extract_epi8
 * [ ] _mm_extract_epi32
 * [ ] _mm_extract_epi64
 * [ ] _mm_insert_ps
 * [ ] _mm_insert_epi8
 * [ ] _mm_insert_epi32
 * [ ] _mm_insert_epi64
 * [ ] _mm_mpsadbw_epu8
 * [ ] _mm_cmpistrm
 * [ ] _mm_cmpistri
 * [ ] _mm_cmpistrz
 * [ ] _mm_cmpistrc
 * [ ] _mm_cmpistrs
 * [ ] _mm_cmpistro
 * [ ] _mm_cmpistra
 * [ ] _mm_cmpestrm
 * [ ] _mm_cmpestri
 * [ ] _mm_cmpestrz
 * [ ] _mm_cmpestrc
 * [ ] _mm_cmpestrs
 * [ ] _mm_cmpestro
 * [ ] _mm_cmpestra
 * [ ] _mm256_blend_pd
 * [ ] _mm256_blend_ps
 * [ ] _mm256_dp_ps
 * [ ] _mm256_shuffle_pd
 * [ ] _mm256_shuffle_ps
 * [ ] _mm_cmp_pd
 * [ ] _mm256_cmp_pd
 * [ ] _mm_cmp_ps
 * [ ] _mm256_cmp_ps
 * [ ] _mm_cmp_sd
 * [ ] _mm_cmp_ss
 * [ ] _mm256_extractf128_ps
 * [ ] _mm256_extractf128_pd
 * [ ] _mm256_extractf128_si256
 * [ ] _mm256_permute_ps
 * [ ] _mm_permute_ps
 * [ ] _mm256_permute_pd
 * [ ] _mm_permute_pd
 * [ ] _mm256_permute2f128_ps
 * [ ] _mm256_permute2f128_pd
 * [ ] _mm256_permute2f128_si256
 * [ ] _mm256_insertf128_ps
 * [ ] _mm256_insertf128_pd
 * [ ] _mm256_insertf128_si256
 * [ ] _mm256_alignr_epi8
 * [ ] _mm256_blend_epi16
 * [ ] _mm_blend_epi32
 * [ ] _mm256_blend_epi32
 * [ ] _mm256_extracti128_si256
 * [ ] _mm256_inserti128_si256
 * [ ] _mm256_mpsadbw_epu8
 * [ ] _mm256_permute2x128_si256
 * [ ] _mm256_permute4x64_epi64
 * [ ] _mm256_permute4x64_pd
 * [ ] _mm256_shuffle_epi32
 * [ ] _mm256_shufflehi_epi16
 * [ ] _mm256_shufflelo_epi16
 * [ ] _mm256_slli_si256
 * [ ] _mm256_bslli_epi128
 * [ ] _mm256_slli_epi16
 * [ ] _mm256_slli_epi32
 * [ ] _mm256_slli_epi64
 * [ ] _mm256_srai_epi16
 * [ ] _mm256_srai_epi32
 * [ ] _mm256_srli_si256
 * [ ] _mm256_bsrli_epi128
 * [ ] _mm256_srli_epi16
 * [ ] _mm256_srli_epi32
 * [ ] _mm256_srli_epi64

**Comment by mr-c** [comment]
@nemequ Can you be a bit more specific on how to check one of these? These instructions will also need to go into https://github.com/nemequ/simde/wiki/Implementing-a-New-Function

**Comment by ashnewmanjones** [comment]
Hi,

I have been taking a look at this issue and had a couple questions about how to implement any changes.

- Is it only the 4 compilers in the linked Compiler Explorer that need to be checked? If not what others should I check?
- I have looked at some functions e.g. _mm256_srli_epi16 and there is a `SIMDE_REQUIRE_CONSTANT_RANGE` macro already , however looking at the compilers they don't require a constant so should these be reduced to just `SIMDE_REQUIRE_RANGE`?

Let me know and I'm happy to go through these and send some PR's.

**Comment by nemequ** [comment]
>     * Is it only the 4 compilers in the linked Compiler Explorer that need to be checked? If not what others should I check?

GCC, clang, ICC, and MSVC should be enough.  There are a few other compilers which support x86 vector intrinsics, but they aren't currently supported, at least explicitly.

>     * I have looked at some functions e.g. _mm256_srli_epi16 and there is a `SIMDE_REQUIRE_CONSTANT_RANGE` macro already , however looking at the compilers they don't require a constant so should these be reduced to just `SIMDE_REQUIRE_RANGE`?

Yes, it is definitely possible that in some case cases we have `SIMDE_REQUIRE_CONSTANT_RANGE` but it should be `SIMDE_REQUIRE_RANGE`.  It's possible that some compilers may have once require a constant but no longer do, though, so don't be surprised if you change one of these and end up with an error in CI because of an older (or newer) version.  That's not a problem, I just don't want you to be surprised :)

> Let me know and I'm happy to go through these and send some PR's.

Thanks, that would be great☺.

**Comment by nemequ** [comment]
@ashnewmanjones, did you do all of these in #614? I'm wondering if I can close the issue, or if there are still some remaining…

**Comment by ashnewmanjones** [comment]
@nemequ, Yes I checked them all except what I listed in #614.
