### ISSUE TITLE
Ubuntu Xenial 16.04 LTS, clang 3.8, fatal error: error in backend: Cannot select: 0xc153370: v64i8 = X86ISD::VPERMV 0xc14d310, 0xc1535d0

### ISSUE THREAD

**Issue by mr-c** [simd-everywhere/simde#300]
https://github.com/nemequ/simde/commit/6d3ca40408aec20c9090b7c47ae7062805ee94f3

https://travis-ci.org/github/nemequ/simde/jobs/688413580#L571

**Comment by nemequ** [comment]
Sorry, but there is no way we can work around this; this isn't a simple case of one function generating bad code, it happens whenever we set the value of a 128-bit vector while AVX-512VL is enabled.

For example, this reproduces the issue:

```c
typedef int32_t;
typedef simde_float32;

typedef struct {
  int32_t i32 __attribute__((__vector_size__(16)));
  simde_float32 f32 __attribute__((__vector_size__(16)))
} simde__m128_private;

simde__m128_private test_simde_mm_cmpge_ps_r_, test_simde_mm_cmpge_ps_a_,
    test_simde_mm_cmpge_ps_b_;
fn1() {
  test_simde_mm_cmpge_ps_r_.i32 =
      test_simde_mm_cmpge_ps_a_.f32 >= test_simde_mm_cmpge_ps_b_.f32;
}
```

If you want to auto-vectorize to avx512 targets I think you're going to need to upgrade to at least 3.9, which seems to have fixed this issue.  That said, this is really only a problem if you're targeting AVX-512VL but don't allow SIMDe to use the native implementations (i.e., `-mavx512vl -DSIMDE_NO_NATIVE`) so it is mostly only a problem for our test cases.

**Comment by mr-c** [comment]
This version of clang is part of a still supported Ubuntu LTS release, so we need to update the documentation to be clear about what is and is not expected.

**Comment by nemequ** [comment]
This problem is documented on the wiki now: https://github.com/simd-everywhere/simde/wiki/Compiler-Bugs#clang
