### ISSUE TITLE
SVML functions

### ISSUE THREAD

**Issue by nemequ** [simd-everywhere/simde#40]
I've been hesitating on this one because I expect many of them to be a bit painful to implement, but [SVML](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#techs=SVML) support would be a pretty nice addition to SIMDe:

 - [x] _mm256_acos_pd
 - [x] _mm256_acos_ps
 - [x] _mm256_acosh_pd
 - [x] _mm256_acosh_ps
 - [x] _mm256_asin_pd
 - [x] _mm256_asin_ps
 - [x] _mm256_asinh_pd
 - [x] _mm256_asinh_ps
 - [x] _mm256_atan_pd
 - [x] _mm256_atan_ps
 - [x] _mm256_atan2_pd
 - [x] _mm256_atan2_ps
 - [x] _mm256_atanh_pd
 - [x] _mm256_atanh_ps
 - [x] _mm256_cbrt_pd
 - [x] _mm256_cbrt_ps
 - [x] _mm256_cdfnorm_pd
 - [x] _mm256_cdfnorm_ps
 - [x] _mm256_cdfnorminv_pd
 - [x] _mm256_cdfnorminv_ps
 - [x] _mm256_cexp_ps
 - [x] _mm256_clog_ps
 - [x] _mm256_cos_pd
 - [x] _mm256_cos_ps
 - [x] _mm256_cosd_pd
 - [x] _mm256_cosd_ps
 - [x] _mm256_cosh_pd
 - [x] _mm256_cosh_ps
 - [x] _mm256_csqrt_ps
 - [x] _mm256_div_epi8
 - [x] _mm256_div_epi16
 - [x] _mm256_div_epi32
 - [x] _mm256_div_epi64
 - [x] _mm256_div_epu8
 - [x] _mm256_div_epu16
 - [x] _mm256_div_epu32
 - [x] _mm256_div_epu64
 - [x] _mm256_erf_pd
 - [x] _mm256_erf_ps
 - [x] _mm256_erfc_pd
 - [x] _mm256_erfc_ps
 - [x] _mm256_erfcinv_pd
 - [x] _mm256_erfcinv_ps
 - [x] _mm256_erfinv_pd
 - [x] _mm256_erfinv_ps
 - [x] _mm256_exp_pd
 - [x] _mm256_exp_ps
 - [x] _mm256_exp10_pd
 - [x] _mm256_exp10_ps
 - [x] _mm256_exp2_pd
 - [x] _mm256_exp2_ps
 - [x] _mm256_expm1_pd
 - [x] _mm256_expm1_ps
 - [x] _mm256_hypot_pd
 - [x] _mm256_hypot_ps
 - [x] _mm256_idiv_epi32
 - [x] _mm256_idivrem_epi32
 - [x] _mm256_invcbrt_pd
 - [x] _mm256_invcbrt_ps
 - [x] _mm256_invsqrt_pd
 - [x] _mm256_invsqrt_ps
 - [x] _mm256_irem_epi32
 - [x] _mm256_log_pd
 - [x] _mm256_log_ps
 - [x] _mm256_log10_pd
 - [x] _mm256_log10_ps
 - [x] _mm256_log1p_pd
 - [x] _mm256_log1p_ps
 - [x] _mm256_log2_pd
 - [x] _mm256_log2_ps
 - [x] _mm256_logb_pd
 - [x] _mm256_logb_ps
 - [x] _mm256_pow_pd
 - [x] _mm256_pow_ps
 - [x] _mm256_rem_epi8
 - [x] _mm256_rem_epi16
 - [x] _mm256_rem_epi32
 - [x] _mm256_rem_epi64
 - [x] _mm256_rem_epu8
 - [x] _mm256_rem_epu16
 - [x] _mm256_rem_epu32
 - [x] _mm256_rem_epu64
 - [x] _mm256_sin_pd
 - [x] _mm256_sin_ps
 - [x] _mm256_sincos_pd
 - [x] _mm256_sincos_ps
 - [x] _mm256_sind_pd
 - [x] _mm256_sind_ps
 - [x] _mm256_sinh_pd
 - [x] _mm256_sinh_ps
 - [x] _mm256_svml_ceil_pd
 - [x] _mm256_svml_ceil_ps
 - [x] _mm256_svml_floor_pd
 - [x] _mm256_svml_floor_ps
 - [x] _mm256_svml_round_pd
 - [x] _mm256_svml_round_ps
 - [x] _mm256_svml_sqrt_pd
 - [x] _mm256_svml_sqrt_ps
 - [x] _mm256_tan_pd
 - [x] _mm256_tan_ps
 - [x] _mm256_tand_pd
 - [x] _mm256_tand_ps
 - [x] _mm256_tanh_pd
 - [x] _mm256_tanh_ps
 - [x] _mm256_trunc_pd
 - [x] _mm256_trunc_ps
 - [x] _mm256_udiv_epi32
 - [x] _mm256_udivrem_epi32
 - [x] _mm256_urem_epi32
 - [x] _mm512_acos_pd
 - [x] _mm512_mask_acos_pd
 - [x] _mm512_acos_ps
 - [x] _mm512_mask_acos_ps
 - [x] _mm512_acosh_pd
 - [x] _mm512_mask_acosh_pd
 - [x] _mm512_acosh_ps
 - [x] _mm512_mask_acosh_ps
 - [x] _mm512_asin_pd
 - [x] _mm512_mask_asin_pd
 - [x] _mm512_asin_ps
 - [x] _mm512_mask_asin_ps
 - [x] _mm512_asinh_pd
 - [x] _mm512_mask_asinh_pd
 - [x] _mm512_asinh_ps
 - [x] _mm512_mask_asinh_ps
 - [x] _mm512_atan2_pd
 - [x] _mm512_mask_atan2_pd
 - [x] _mm512_atan2_ps
 - [x] _mm512_mask_atan2_ps
 - [x] _mm512_atan_pd
 - [x] _mm512_mask_atan_pd
 - [x] _mm512_atan_ps
 - [x] _mm512_mask_atan_ps
 - [x] _mm512_atanh_pd
 - [x] _mm512_mask_atanh_pd
 - [x] _mm512_atanh_ps
 - [x] _mm512_mask_atanh_ps
 - [x] _mm512_cbrt_pd
 - [x] _mm512_mask_cbrt_pd
 - [x] _mm512_cbrt_ps
 - [x] _mm512_mask_cbrt_ps
 - [x] _mm512_cdfnorm_pd
 - [x] _mm512_mask_cdfnorm_pd
 - [x] _mm512_cdfnorm_ps
 - [x] _mm512_mask_cdfnorm_ps
 - [x] _mm512_cdfnorminv_pd
 - [x] _mm512_mask_cdfnorminv_pd
 - [x] _mm512_cdfnorminv_ps
 - [x] _mm512_mask_cdfnorminv_ps
 - [x] _mm512_ceil_pd
 - [x] _mm512_mask_ceil_pd
 - [x] _mm512_ceil_ps
 - [x] _mm512_mask_ceil_ps
 - [x] _mm512_cos_pd
 - [x] _mm512_mask_cos_pd
 - [x] _mm512_cos_ps
 - [x] _mm512_mask_cos_ps
 - [x] _mm512_cosd_pd
 - [x] _mm512_mask_cosd_pd
 - [x] _mm512_cosd_ps
 - [x] _mm512_mask_cosd_ps
 - [x] _mm512_cosh_pd
 - [x] _mm512_mask_cosh_pd
 - [x] _mm512_cosh_ps
 - [x] _mm512_mask_cosh_ps
 - [x] _mm512_erf_pd
 - [x] _mm512_mask_erf_pd
 - [x] _mm512_erfc_pd
 - [x] _mm512_mask_erfc_pd
 - [x] _mm512_erf_ps
 - [x] _mm512_mask_erf_ps
 - [x] _mm512_erfc_ps
 - [x] _mm512_mask_erfc_ps
 - [x] _mm512_erfinv_pd
 - [x] _mm512_mask_erfinv_pd
 - [x] _mm512_erfinv_ps
 - [x] _mm512_mask_erfinv_ps
 - [x] _mm512_erfcinv_pd
 - [x] _mm512_mask_erfcinv_pd
 - [x] _mm512_erfcinv_ps
 - [x] _mm512_mask_erfcinv_ps
 - [x] _mm512_exp10_pd
 - [x] _mm512_mask_exp10_pd
 - [x] _mm512_exp10_ps
 - [x] _mm512_mask_exp10_ps
 - [x] _mm512_exp2_pd
 - [x] _mm512_mask_exp2_pd
 - [x] _mm512_exp2_ps
 - [x] _mm512_mask_exp2_ps
 - [x] _mm512_exp_pd
 - [x] _mm512_mask_exp_pd
 - [x] _mm512_exp_ps
 - [x] _mm512_mask_exp_ps
 - [x] _mm512_expm1_pd
 - [x] _mm512_mask_expm1_pd
 - [x] _mm512_expm1_ps
 - [x] _mm512_mask_expm1_ps
 - [x] _mm512_floor_pd
 - [x] _mm512_mask_floor_pd
 - [x] _mm512_floor_ps
 - [x] _mm512_mask_floor_ps
 - [x] _mm512_hypot_pd
 - [x] _mm512_mask_hypot_pd
 - [x] _mm512_hypot_ps
 - [x] _mm512_mask_hypot_ps
 - [x] _mm512_div_epi32
 - [x] _mm512_mask_div_epi32
 - [x] _mm512_div_epi8
 - [x] _mm512_div_epi16
 - [x] _mm512_div_epi64
 - [x] _mm512_invsqrt_pd
 - [x] _mm512_mask_invsqrt_pd
 - [x] _mm512_invsqrt_ps
 - [x] _mm512_mask_invsqrt_ps
 - [x] _mm512_rem_epi32
 - [x] _mm512_mask_rem_epi32
 - [x] _mm512_rem_epi8
 - [x] _mm512_rem_epi16
 - [x] _mm512_rem_epi64
 - [x] _mm512_log10_pd
 - [x] _mm512_mask_log10_pd
 - [x] _mm512_log10_ps
 - [x] _mm512_mask_log10_ps
 - [x] _mm512_log1p_pd
 - [x] _mm512_mask_log1p_pd
 - [x] _mm512_log1p_ps
 - [x] _mm512_mask_log1p_ps
 - [x] _mm512_log2_pd
 - [x] _mm512_mask_log2_pd
 - [x] _mm512_log_pd
 - [x] _mm512_mask_log_pd
 - [x] _mm512_log_ps
 - [x] _mm512_mask_log_ps
 - [x] _mm512_logb_pd
 - [x] _mm512_mask_logb_pd
 - [x] _mm512_logb_ps
 - [x] _mm512_mask_logb_ps
 - [x] _mm512_nearbyint_pd
 - [x] _mm512_mask_nearbyint_pd
 - [x] _mm512_nearbyint_ps
 - [x] _mm512_mask_nearbyint_ps
 - [x] _mm512_pow_pd
 - [x] _mm512_mask_pow_pd
 - [x] _mm512_pow_ps
 - [x] _mm512_mask_pow_ps
 - [x] _mm512_recip_pd
 - [x] _mm512_mask_recip_pd
 - [x] _mm512_recip_ps
 - [x] _mm512_mask_recip_ps
 - [x] _mm512_rint_pd
 - [x] _mm512_mask_rint_pd
 - [x] _mm512_rint_ps
 - [x] _mm512_mask_rint_ps
 - [x] _mm512_svml_round_pd
 - [x] _mm512_mask_svml_round_pd
 - [x] _mm512_sin_pd
 - [x] _mm512_mask_sin_pd
 - [x] _mm512_sin_ps
 - [x] _mm512_mask_sin_ps
 - [x] _mm512_sinh_pd
 - [x] _mm512_mask_sinh_pd
 - [x] _mm512_sinh_ps
 - [x] _mm512_mask_sinh_ps
 - [x] _mm512_sind_pd
 - [x] _mm512_mask_sind_pd
 - [x] _mm512_sind_ps
 - [x] _mm512_mask_sind_ps
 - [x] _mm512_tan_pd
 - [x] _mm512_mask_tan_pd
 - [x] _mm512_tan_ps
 - [x] _mm512_mask_tan_ps
 - [x] _mm512_tand_pd
 - [x] _mm512_mask_tand_pd
 - [x] _mm512_tand_ps
 - [x] _mm512_mask_tand_ps
 - [x] _mm512_tanh_pd
 - [x] _mm512_mask_tanh_pd
 - [x] _mm512_tanh_ps
 - [x] _mm512_mask_tanh_ps
 - [x] _mm512_trunc_pd
 - [x] _mm512_mask_trunc_pd
 - [x] _mm512_trunc_ps
 - [x] _mm512_mask_trunc_ps
 - [x] _mm512_div_epu32
 - [x] _mm512_mask_div_epu32
 - [x] _mm512_div_epu8
 - [x] _mm512_div_epu16
 - [x] _mm512_div_epu64
 - [x] _mm512_rem_epu32
 - [x] _mm512_mask_rem_epu32
 - [x] _mm512_rem_epu8
 - [x] _mm512_rem_epu16
 - [x] _mm512_rem_epu64
 - [x] _mm512_sincos_pd
 - [x] _mm512_mask_sincos_pd
 - [x] _mm512_sincos_ps
 - [x] _mm512_mask_sincos_ps
 - [x] _mm_acos_pd
 - [x] _mm_acos_ps
 - [x] _mm_acosh_pd
 - [x] _mm_acosh_ps
 - [x] _mm_asin_pd
 - [x] _mm_asin_ps
 - [x] _mm_asinh_pd
 - [x] _mm_asinh_ps
 - [x] _mm_atan_pd
 - [x] _mm_atan_ps
 - [x] _mm_atan2_pd
 - [x] _mm_atan2_ps
 - [x] _mm_atanh_pd
 - [x] _mm_atanh_ps
 - [x] _mm_cbrt_pd
 - [x] _mm_cbrt_ps
 - [x] _mm_cdfnorm_pd
 - [x] _mm_cdfnorm_ps
 - [x] _mm_cdfnorminv_pd
 - [x] _mm_cdfnorminv_ps
 - [x] _mm_cexp_ps
 - [x] _mm_clog_ps
 - [x] _mm_cos_pd
 - [x] _mm_cos_ps
 - [x] _mm_cosd_pd
 - [x] _mm_cosd_ps
 - [x] _mm_cosh_pd
 - [x] _mm_cosh_ps
 - [x] _mm_csqrt_ps
 - [x] _mm_div_epi8
 - [x] _mm_div_epi16
 - [x] _mm_div_epi32
 - [x] _mm_div_epi64
 - [x] _mm_div_epu8
 - [x] _mm_div_epu16
 - [x] _mm_div_epu32
 - [x] _mm_div_epu64
 - [x] _mm_erf_pd
 - [x] _mm_erf_ps
 - [x] _mm_erfc_pd
 - [x] _mm_erfc_ps
 - [x] _mm_erfcinv_pd
 - [x] _mm_erfcinv_ps
 - [x] _mm_erfinv_pd
 - [x] _mm_erfinv_ps
 - [x] _mm_exp_pd
 - [x] _mm_exp_ps
 - [x] _mm_exp10_pd
 - [x] _mm_exp10_ps
 - [x] _mm_exp2_pd
 - [x] _mm_exp2_ps
 - [x] _mm_expm1_pd
 - [x] _mm_expm1_ps
 - [x] _mm_hypot_pd
 - [x] _mm_hypot_ps
 - [x] _mm_idiv_epi32
 - [x] _mm_idivrem_epi32
 - [x] _mm_invcbrt_pd
 - [x] _mm_invcbrt_ps
 - [x] _mm_invsqrt_pd
 - [x] _mm_invsqrt_ps
 - [x] _mm_irem_epi32
 - [x] _mm_log_pd
 - [x] _mm_log_ps
 - [x] _mm_log10_pd
 - [x] _mm_log10_ps
 - [x] _mm_log1p_pd
 - [x] _mm_log1p_ps
 - [x] _mm_log2_pd
 - [x] _mm_log2_ps
 - [x] _mm_logb_pd
 - [x] _mm_logb_ps
 - [x] _mm_pow_pd
 - [x] _mm_pow_ps
 - [x] _mm_rem_epi8
 - [x] _mm_rem_epi16
 - [x] _mm_rem_epi32
 - [x] _mm_rem_epi64
 - [x] _mm_rem_epu8
 - [x] _mm_rem_epu16
 - [x] _mm_rem_epu32
 - [x] _mm_rem_epu64
 - [x] _mm_sin_pd
 - [x] _mm_sin_ps
 - [x] _mm_sincos_pd
 - [x] _mm_sincos_ps
 - [x] _mm_sind_pd
 - [x] _mm_sind_ps
 - [x] _mm_sinh_pd
 - [x] _mm_sinh_ps
 - [x] _mm_svml_ceil_pd
 - [x] _mm_svml_ceil_ps
 - [x] _mm_svml_floor_pd
 - [x] _mm_svml_floor_ps
 - [x] _mm_svml_round_pd
 - [x] _mm_svml_round_ps
 - [x] _mm_svml_sqrt_pd
 - [x] _mm_svml_sqrt_ps
 - [x] _mm_tan_pd
 - [x] _mm_tan_ps
 - [x] _mm_tand_pd
 - [x] _mm_tand_ps
 - [x] _mm_tanh_pd
 - [x] _mm_tanh_ps
 - [x] _mm_trunc_pd
 - [x] _mm_trunc_ps
 - [x] _mm_udiv_epi32
 - [x] _mm_udivrem_epi32
 - [x] _mm_urem_epi32

**Comment by mr-c** [comment]
Congratulations @himanshi18037 !

**Comment by himanshi18037** [comment]
> Congratulations @himanshi18037 !

Thanks:) @mr-c

**Comment by nemequ** [comment]
This is finished; great job @himanshi18037!
