### ISSUE TITLE
0.5.1 release for clang11 fix?

### ISSUE THREAD

**Issue by mr-c** [simd-everywhere/simde#490]
https://github.com/simd-everywhere/simde/commit/e5b5b7db97892a378fa6d2714b299791c4c5eb10 

And it looks like avx2 might be done soon too :-)

**Comment by nemequ** [comment]
To be clear, it's not clang 11 that is the problem, it's Apple Clang 11, which is a fork of a pre-release version of an older version of clang (7 or 8, IIRC) which had a bug.  The clang people fixed it before their release, but Apple didn't back-port the fix.

But yes I'll try to make another release soon.  I need to put out a new release of Hedley, too, and I'd like to do that first so those fixes are in SIMDe, too.

**Comment by mr-c** [comment]
https://github.com/simd-everywhere/simde/commit/63d87d9604e025816aed575afe6cf6a46d79635d this would also justify a 0.5.1 release on its own. I can can cherry pick it for Debian but a release would be nicer 🙂

**Comment by nemequ** [comment]
Yeah, I was thinking that too.  I'll try to put out a release in the next day or two.

**Comment by mr-c** [comment]
Gentle ping for a new release :-)

**Comment by nemequ** [comment]
Just released 0.6.0, sorry about the delay.

**Comment by mr-c** [comment]
Thank you @nemequ! I see the tag, but no GitHub release, so I'm doing that part myself.

**Comment by nemequ** [comment]
Thanks. I thought creating a tag created a new release, guess not :/
