### ISSUE TITLE
Design a better logo

### ISSUE THREAD

**Issue by nemequ** [simd-everywhere/simde#502]
"Better" really isn't a high bar; the current one is hideous.

My design sklls are… well, I created the current logo, which pretty much says it all.  So I'm going to slap a "help wanted" label on this and just hope for the best ;)

**Comment by seanptmaher** [comment]
[Here](https://drive.google.com/file/d/1RoeXNnnIjB_OhpEB9vznGy5opMny8jsd/view?usp=sharing) is the result of fidding around in gimp for 5 minutes, it's the only "stye" that came to mind right away.

**Comment by masterchef2209** [comment]
> "Better" really isn't a high bar; the current one is hideous.

Maybe this is my unpopular opinion but I actually like the current design. It is very minimalistic and looks good. That being said, if I get some good idea I will try to make something.

**Comment by nemequ** [comment]
> [Here](https://drive.google.com/file/d/1RoeXNnnIjB_OhpEB9vznGy5opMny8jsd/view?usp=sharing) is the result of fidding around in gimp for 5 minutes, it's the only "stye" that came to mind right away.

I like the inverted e.  Not crazy about the font (the S and the e seem off to me).  I definitely think it's an improvement over the current version.

Mine was also the result of fiddling around it gimp for 5 minutes; the automatically generated avatar for the organization was really ugly, so I just wanted something quickly.  That probably explains why I went for something more square.  I think you made better use of your 5 minutes than I did, though :)

> Maybe this is my unpopular opinion but I actually like the current design. It is very minimalistic and looks good. That being said, if I get some good idea I will try to make something.

I do like the minimalism, but I think it's a bit painful to look at.  I do sort of like the ∈ (member of) instead of a normal E, but I'm not sure how many people would really notice that as opposed to just thinking it's a weird font…

Working off Sean's idea, maybe something like

![Horizontal](https://user-images.githubusercontent.com/1151/87839345-f5e93e80-c889-11ea-9016-47d57fd48335.png)

Or

![Vectical](https://user-images.githubusercontent.com/1151/87839352-feda1000-c889-11ea-93d5-d31331093d36.png)

**Comment by masterchef2209** [comment]
> I do sort of like the ∈ (member of) instead of a normal E, but I'm not sure how many people would really notice that as opposed to just thinking it's a weird font…

I noticed it :)


> Working off Sean's idea, maybe something like

Second one looks great imo.

**Comment by seanptmaher** [comment]
You should add a white background if you upload it. Normal github does have a white background, but for me, I have a usercss to make it dark and it's hardly legible.

**Comment by nemequ** [comment]
I went ahead with a slightly modified version of what I posted earlier (moved some stuff around to make it square and look a bit better, and got rid of the transparent background as Sean suggested).

Sean, the way I see it most of the credit goes to you since mine is really just a variation on your idea.  Do you have any thoughts about the license?  I'm not sure MIT works because it's a graphic not code (though that would be okay with me if it's what you prefer), so maybe CC-BY-SA?

**Comment by seanptmaher** [comment]
I think if you were to use CC-BY-SA, [Google wouldn't be able to use it](https://opensource.google/docs/thirdparty/licenses/#banned), so, whatever you could find that isn't listed in that page would be ideal, but I don't have a further opinion regarding the choice, so go with whatever you like.

**Comment by nemequ** [comment]
CC-BY-SA (by-attribution / share-alike) should be fine; it's the NC (non-commercial) variant they can't use.
