### ISSUE TITLE
Please make tests conditional on a build-time variable

### ISSUE THREAD

**Issue by yurivict** [simd-everywhere/simde#544]
Tests shouldn't be built during packaging.

**Comment by nemequ** [comment]
This is already done, added in 32d1a4f047dacef7c8548f4ccccf8deabe41dd6b#diff-f2ff94c68cbdd606743b339aa68a4164.  `meson -Dtests=false ...`

**Comment by nemequ** [comment]
FWIW I intend to put out a new release soon, which will include this change.  Probably over the weekend, maybe early next week.

**Comment by yurivict** [comment]
Thanks.
