### ISSUE TITLE
Add macro to detect IEEE 754 storage

### ISSUE THREAD

**Issue by nemequ** [simd-everywhere/simde#558]
We have several functions which need to detect whether a number is stored using IEEE 754 in order to enable optimizations, mostly for approximate methods.

Currently we use `defined(__STDC_IEC_559__)` to detect this, but that actually isn't defined if you use -ffast-math.  What we need is a way to detect (at compile time) whether floating point values are *stored* using IEEE 754, even if the implementation isn't strictly compliant (i.e., -ffast-math).

I'd like to figure out a way other than just looking at the target architecture, but I'm not sure that will be possible in the preprocessor.  We could fall back on a compile-time non-preprocessor test, something like (untested)

```c
union {
  float as_float;
  uint32_t as_uint;
} simde_x_float_ieee754_pi_ = { 
  SIMDE_MATH_PIF
};

#define SIMDE_FLOAT_IS_IEEE754 (simde_x_float_ieee754_pi_.as_uint == 0x40490fdb)
```

But I'd rather be able to use it in the preprocessor, for consistency if nothing else.

**Comment by Artoria2e5** [comment]
`__STDC_IEC_60559_BFP__` might be a closer fit to this requirement, but again I am not sure about who supports it.
