### ISSUE TITLE
Travis CI no longer running due to new caps

### ISSUE THREAD

**Issue by mr-c** [simd-everywhere/simde#649]
> -1680 available credits (purchase date: November 23, 2020)
>
> You have used 11680 of 10000 credits 

> Builds have been temporarily disabled for public repositories due to a negative credit balance. Please go to the Plan page to replenish your credit balance or alter your Consume paid credits for OSS setting. 

For CWL I emailed support@travis-ci.com to ask for additional credits.

Here is the information they requested

> Thanks for contacting Travis-CI Support! I’d love to help! We offer an Open Source/Educational Subscription for free to non-commercial Open Source projects. To qualify for an OSS subscription, the project must meet the following requirements:

>    You are a project lead or regular committer (latest commit in the last month)
    Project must be at least 3 months old and is in active development (with regular commits and activity)
    Project meets the OSD specification
    Project must not be sponsored by a commercial company or organization (monetary or with employees paid to work on the project)
    Project can not provide commercial services or distribute paid versions of the software

@nemequ I think you should be the requester

**Comment by nemequ** [comment]
Here is the last message I got from them, on December 3:

> Thanks for your patience while we worked on your request.
>
> We are awaiting further approval for your account and will promptly apply credits as directed to your account.
>
> In the meantime, however, we have added 50,000 credits to your account to enable you continue using the service. I hope this helps.
>
> Thanks and we will follow up soon.

We've gone through those credits already, and I haven't even been contributing lately.  I have no idea when they'll make a final determination, but I think that we're going to need to significantly scale back our usage of Travis.  I already moved most of the low-hanging fruit over to GitHub Actions since it's so much faster, but I think we're going to have to get rid of all but maybe a couple of the remaining builds.

**Comment by mr-c** [comment]
> We've gone through those credits already

:-(

For my other projects, I've made personal forks and run Travis there, while we finish the migration to GitHub Actions.

**Comment by nemequ** [comment]
Travis has been removed.  Most bulids have been migrated to other providers, though a few (ppc64le and s/390 for example) don't have good replacements because nobody else has the right hardware.
