### ISSUE TITLE
Support for FP16C

### ISSUE THREAD

**Issue by jdumas** [simd-everywhere/simde#651]
Hi there,

I'm curious if you had any plan to add support for half-precision instructions? I think there are only 4 functions:

- [ ] `_mm_cvtph_ps`
- [ ] `_mm256_cvtph_ps`
- [ ] `_mm_cvtps_ph`
- [ ] `_mm256_cvtps_ph`

**Comment by nemequ** [comment]
Sure.  We plan to add support to for *all* the vector functions, it's just a matter of time.  x86 alone has ~6200 functions (~2100 are in SIMDe), and NEON ~4350 (~1800 are in SIMDe).

If you need them for something I can prioritize them. It doesn't really matter to me which functions we do first, so I figure I may as well start with those that people will actually use…  Or, if you're interested you could always [implement them](https://github.com/simd-everywhere/simde/wiki/Implementing-a-New-Function).

**Comment by jdumas** [comment]
Yeah, it's quite a long list, I'm already impressed by everything you've covered so far :D
Idk if I'll have the time to give it a shot myself, but I'll ping you again if I do.

**Comment by nemequ** [comment]
Fixed by 62c1087fa02e56cc69746e6ce4d26a9721e33ad0.  Sorry, forgot to close this :(

**Comment by jdumas** [comment]
Awesome, thanks!
