### ISSUE TITLE
gcc 11 snapshot + amd64: sse2 simde_x_mm_loadu_si{16,32}: test failure

### ISSUE THREAD

**Issue by mr-c** [simd-everywhere/simde#674]
```
test/x86/sse2.cpp:4326: assertion failed: r[0] == simde_x_mm_loadu_epi16(test_vec[i].r)[0] (0 == -11138)
test/x86/sse2.cpp:4359: assertion failed: r[0] == simde_x_mm_loadu_epi32(test_vec[i].r)[0] (0 == 418822831)
```
GCC snapshot, taken from the trunk (20201216)

https://metadata.ftp-master.debian.org/changelogs//main/g/gcc-11/gcc-11_11-20201216-2_changelog

**Comment by mr-c** [comment]
Full log

https://buildd.debian.org/status/fetch.php?pkg=simde&arch=amd64&ver=0.7.0%7Erc-2-1&stamp=1608654198&raw=0

**Comment by junaruga** [comment]
I faced this issue on gcc 11 x86_64 on Fedora.

I applied the patch to skip the assert functions like this in the simde RPM spec file (recipe file), as I did not know how to skip the code.

```
# The sse2 tests fail on gcc 11, x86_64.
# https://github.com/simd-everywhere/simde/issues/674
sed -i '/^test_simde_mm_loadu_si16/,/^}$/ s|simde_test_x86_assert_equal_i16x8|//\0|' test/x86/sse2.c
sed -i '/^test_simde_mm_loadu_si32/,/^}$/ s|simde_test_x86_assert_equal_i32x4|//\0|' test/x86/sse2.c
```

**Comment by nemequ** [comment]
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=99754

**Comment by junaruga** [comment]
Thanks! I confirmed it was fixed on the latest master.
