### ISSUE TITLE
GSoC 2021 Ideas

### ISSUE THREAD

**Issue by nemequ** [simd-everywhere/simde#702]
GSoC 2021 is coming up, and if SIMDe is going to participate again we need some project ideas.  GSoC this year is going to be a bit different, with each project being roughly half the size.  I think this could work well for SIMDe since we have lots of flexibility in how large a project is; we could just say implement N functions (or families of functions).  This is a bit simpler than last year where we tried to choose extensions which weren't too large or too small.

I think that with the Docker development container we have now the setup should be quite a bit easier this year, so students should be able to get up and running a bit more easily than last year.

As far as ideas, the obvious thing is just implementing more stuff.  NEON still has a long way to go, as does AVX-512 on the x86 side of things. There is *plenty* to do here.

Another idea would be implementing all the *_f16 NEON functions we have skipped for the existing implementations. Support for 16-bit floats is a very recent addition to SIMDe, and until it was in place we just skipped those functions.  Right now only the x86 side of things is really done (the f16c extension is fully supported, though avx-512 adds some more functions for longer vectors which are not yet implemented, but that's *really* easy).  I'm not sure this would be quite enough to take up a whole GSoC task, but we could always request they also implement a few new function families.

There is also porting all the x86 stuff from emscripten; that would mean going through all the functions they have implemented and, if their implementations are better (or we are relying exclusively on the portable version), copy them into SIMDe.  It would also require carefully updating the documentation since they want a very clear list explaining what functions are fast on which platforms.

Anyone else have any other ideas?

As far as mentors go, I'm willing to do it again this year.  @mr-c may or may not be interested, and I believe @ngzhian may be interested this as well.  If anyone is interested, please let me know.  Also, if you have a preferred project you'd like to mentor that's of course

**Comment by mr-c** [comment]
A free idea, but I'm unable to mentor much for it:

Benchmark the SIMDe implementations using a real (bioinformatic?) application that was written for x86-64 but compiled for AWS Graviton and Apple Silicon using SIMDe

**Comment by ngzhian** [comment]
I will be happy to mentor a student to continue working on what Sean did, implementing ARM intrinsics.

**Comment by nemequ** [comment]
> Benchmark the SIMDe implementations using a real (bioinformatic?) application that was written for x86-64 but compiled for AWS Graviton and Apple Silicon using SIMDe

I don't think this is big enough to be a complete project, but it would be interesting.  Maybe find a (bioinformatic?) project which is interested in a SIMDe port, and do both the port and the benchmark?  It would require cooperation with another project, including someone on their side to be a mentor (in addition to someone from SIMDe).

There is also the question of how to compare the performance.  [This tweet](https://twitter.com/BenLangmead/status/1326632403432042496) offers one possibility: price on AWS (or Google Cloud, Azure, whatever…) vs. performance.  I seem to remember Amazon is sometimes willing to offer free EC2 instances for developing OSS.

> I will be happy to mentor a student to continue working on what Sean did, implementing ARM intrinsics.

Awesome, thanks!

**Comment by Glitch18** [comment]
Hey everyone! I would love to work on this project! I went through the project ideas [list](https://www.open-bio.org/events/gsoc/gsoc-project-ideas/) for GSoC 2021, and I would love to contribute here. I also reached out to @nemequ through email. 

I spent the weekend exploring NEON Intrinsics a little, but I would love to know what else can I do to get started, or get to know the project better. I would love to get involved with the community, and contribute to it. 

Thanks!

**Comment by nemequ** [comment]
Hello @Glitch18.  I just responded to your e-mail, but here is an excerpt since I think it contains some decent information for other people who might be interested, too (including for the other project suggestion):

> I think the easiest way to get started would be to use the [SIMDe docker development container](https://github.com/simd-everywhere/simde/tree/master/docker).  I know it works (or at least has worked) from Linux and macOS, and it should work on Windows as well (though it might require you to manually enter some commands instead of using the bash script).  That provides all the emulators you should need so you can easily test the code.
>
> Once you have the docker container set up I would suggest going through the [Implementing a New Function](https://github.com/simd-everywhere/simde/wiki/Implementing-a-New-Function) page on the wiki.  The example is for an x86 function, but the process is basically the same for a NEON function; just take a look at any other NEON function if you need an example.  Also, here is an example of a patch to implement a previously unimplemented function family: https://github.com/simd-everywhere/simde/commit/1bbc67e22cda19766ef8130245f36de879996709#diff-60d426e405a0fcd08b902e426ba35ff53f5b0c14e713e69fb422805bbebd820e
>
> If you have any questions please don't hesitate to reach out; I should be much more responsive now that I have internet access, though I will still be somewhat busy for at least the next few days as I have to unpack and set up all my stuff.  You can also try [our chat room](https://gitter.im/simd-everywhere/community), where there are a few other people who might be able to help as well.

**Comment by nemequ** [comment]
We have a couple great proposals from students this year. We don't yet know how many slots we'll get (or if we'll get any at all), but the time for ideas is done, so I'm closing this.
