### ISSUE TITLE
meson/ninja: how to suppress OK lines in the testing result?

### ISSUE THREAD

**Issue by junaruga** [simd-everywhere/simde#712]
Hello everyone, it's amazing to see this project's growth since 1 year!

I have a question as I started to work on upgrading the simde RPM package on Fedora.

Seeing the `.circleci/config.yml`, I could build and run the tests like this.
But is there way to suppress only the OK lines `N/M path/to/file            OK             N.NNs` printing the ERROR lines and the summarized result?

```
$ CC=gcc CXX=g++ meson setup build

$ ninja -C build -v -j 3

$ ninja -C build -v test
ninja: Entering directory `build'
[0/1] /usr/bin/meson test --no-rebuild --print-errorlogs
  1/882 common/common/c                    OK             0.01s
  2/882 common/common/cpp                  OK             0.01s
...
881/882 arm/neon/zip/emul/cpp              OK             0.01s
882/882 arm/neon/zip/native/cpp            OK             0.01s

Ok:                 882 
Expected Fail:      0   
Fail:               0   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0   

Full log written to /home/jaruga/git/simd-everywhere/simde/build/meson-logs/testlog.txt
```

Thanks!

**Comment by nemequ** [comment]
Hi Jun, nice to see you around :)

I don't think you can do it if you use ninja to run the tests, but you can use meson directly to run the tests (AFAIK ninja really just calls meson here anyways).

```sh
CC=gcc CXX=g++ meson setup build
ninja -C build -v
meson test -q -C build --print-errorlogs
```

**Comment by junaruga** [comment]
@nemequ Hi Evan, nice to see you! Thanks for the info. I will try it and let you know the result here. Thanks!

**Comment by junaruga** [comment]
I confirmed that your suggested way really nicely showed only the summary and the failures without OK lines.

```
CC=gcc CXX=g++ meson setup build
ninja -C build -v
meson test -C build-q --no-rebuild --print-errorlogs
```

I would close this ticket. Thanks!
