### ISSUE TITLE
clang 12 + ppc64le: ninja build error: __float128 is not supported on this target

### ISSUE THREAD

**Issue by junaruga** [simd-everywhere/simde#734]
On the latest master commit: `a558d6d321a1f2b97bc8519f2f5e07a6c02fb29c` with clang 12 + ppc64le, Fedora rawhide (=35), 

I think the situation is moved forward by #716. Thanks! I see the new errors. Could you take a look at it? Thanks.

```
/usr/lib/gcc/ppc64le-redhat-linux/11/../../../../include/c++/11/ext/numeric_traits.h:222:38: error: __float128 is not supported on this target
/usr/lib/gcc/ppc64le-redhat-linux/11/../../../../include/c++/11/ext/numeric_traits.h:230:29: error: __float128 is not supported on this target
/usr/lib/gcc/ppc64le-redhat-linux/11/../../../../include/c++/11/ext/numeric_traits.h:231:40: error: __float128 is not supported on this target
```

```
+ CC=clang
+ CXX=clang++
+ meson setup build/clang
The Meson build system
Version: 0.57.1
Source dir: /builddir/build/BUILD/simde-a558d6d321a1f2b97bc8519f2f5e07a6c02fb29c
Build dir: /builddir/build/BUILD/simde-a558d6d321a1f2b97bc8519f2f5e07a6c02fb29c/build/clang
Build type: native build
Project name: SIMDe
Project version: 0.7.3
C compiler for the host machine: clang (clang 12.0.0 "clang version 12.0.0 (Fedora 12.0.0-0.7.rc3.fc35)")
C linker for the host machine: clang ld.bfd 2.36.1-7
C++ compiler for the host machine: clang++ (clang 12.0.0 "clang version 12.0.0 (Fedora 12.0.0-0.7.rc3.fc35)")
C++ linker for the host machine: clang++ ld.bfd 2.36.1-7
Host machine cpu family: ppc64
Host machine cpu: ppc64le
Library m found: YES
Compiler for C supports arguments -fopenmp-simd: YES- 
Compiler for C++ supports arguments -fopenmp-simd: YES- 
Compiler for C supports arguments -Wpsabi: YES- 
Compiler for C++ supports arguments -Wpsabi: YES- 
Library m found: YES
Build targets in project: 1082 
Found ninja-1.10.2 at /usr/bin/ninja

+ ninja -C build/clang -j 4 
...
[727/2164] Compiling C++ object test/x86/svml-emul-cpp.p/meson-generated_.._svml.cpp.o
FAILED: test/x86/svml-emul-cpp.p/meson-generated_.._svml.cpp.o-
clang++ -Itest/x86/svml-emul-cpp.p -Itest/x86 -I../../test/x86 -I. -I../.. -Xclang -fcolor-diagnostics -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -g -fopenmp-simd -DSIMDE_ENABLE_OPENMP -Wno-psabi -DSIMDE_TEST_BARE -DSIMDE_NO_NATIVE -MD -MQ test/x86/svml-emul-cpp.p/meson-generated_.._svml.cpp.o -MF test/x86/svml-emul-cpp.p/meson-generated_.._svml.cpp.o.d -o test/x86/svml-emul-cpp.p/meson-generated_.._svml.cpp.o -c test/x86/svml.cpp
In file included from test/x86/svml.cpp:27:
In file included from ../../simde/x86/svml.h:50:
In file included from ../../test/x86/../../simde/x86/../simde-complex.h:120:
In file included from /usr/lib/gcc/ppc64le-redhat-linux/11/../../../../include/c++/11/complex:45:
In file included from /usr/lib/gcc/ppc64le-redhat-linux/11/../../../../include/c++/11/sstream:38:
In file included from /usr/lib/gcc/ppc64le-redhat-linux/11/../../../../include/c++/11/istream:38:
In file included from /usr/lib/gcc/ppc64le-redhat-linux/11/../../../../include/c++/11/ios:40:
In file included from /usr/lib/gcc/ppc64le-redhat-linux/11/../../../../include/c++/11/bits/char_traits.h:39:
In file included from /usr/lib/gcc/ppc64le-redhat-linux/11/../../../../include/c++/11/bits/stl_algobase.h:63:
/usr/lib/gcc/ppc64le-redhat-linux/11/../../../../include/c++/11/ext/numeric_traits.h:222:38: error: __float128 is not supported on this target
    struct __numeric_traits_floating<__ieee128>
                                     ^
/usr/lib/gcc/ppc64le-redhat-linux/11/../../../../include/c++/11/ext/numeric_traits.h:230:29: error: __float128 is not supported on this target
    struct __numeric_traits<__ieee128>
                            ^
/usr/lib/gcc/ppc64le-redhat-linux/11/../../../../include/c++/11/ext/numeric_traits.h:231:40: error: __float128 is not supported on this target
    : public __numeric_traits_floating<__ieee128>
                                       ^
3 errors generated.
...
ninja: build stopped: subcommand failed.
```

**Comment by nemequ** [comment]
This looks like a libc++ issue to me.  I don't really have a good way to test clang 12 on ppc64le right now, but it's likely *any* file with an `#include <complex>` would trigger it.

I tried to test, but `docker pull fedora:35` doesn't seem to work for ppc64le (it looks like it's only available for arm64 and amd64). I don't suppose you know an easier way to test than installing a VM and running it in qemu?  I have access to ppc64le hardware, but f35 is tricky…

**Comment by junaruga** [comment]
@nemequ Thanks for the checking!

> I tried to test, but docker pull fedora:35 doesn't seem to work for ppc64le (it looks like it's only available for arm64 and amd64). I don't suppose you know an easier way to test than installing a VM and running it in qemu? I have access to ppc64le hardware, but f35 is tricky…

I was able to use Fedora official container repository's `registry.fedoraproject.org/fedora:35-ppc64le` on QEMU now!

Let me share the steps.

First you need to have a Linux host. Maybe you have it. 

```
$ uname -m
x86_64
```

If you have the Fedora, CentOS (maybe >= 7) or RHEL (>= 7), and you can install the `qemu-user-static` RPM, the RPM installs `/proc/sys/fs/binfmt_misc/qemu-ppc64le` file. And confirm the line: `flags: F` exists.

```
$ cat /proc/sys/fs/binfmt_misc/qemu-ppc64le
enabled
interpreter /usr/bin/qemu-ppc64le-static
flags: F
offset 0
magic 7f454c4602010100000000000000000002001500
mask ffffffffffffff00fffffffffffffffffeffff00
```

If you do not have above Linux distro, the easy way to install the above binfmt_misc file is to use this tool: https://github.com/dbhi/qus . I do not know how to install the binfmt_misc file on Debian based distro. If you are using `docker`, just replace the following command's `podman` with `docker`. And maybe `sudo` is not necessary in case of docker.

```
$ sudo podman run --rm --privileged aptman/qus -s -- -p ppc64le
```

The above command is only to install the following file.

```
$ cat /proc/sys/fs/binfmt_misc/qemu-ppc64le
enabled
interpreter /qus/bin/qemu-ppc64le-static
flags: F
offset 0
magic 7f454c4602010100000000000000000002001500
mask ffffffffffffff00fffffffffffffffffeffff00
```

Then I confirmed that the QEMU emulation works.

```
$ podman run --rm -t registry.fedoraproject.org/fedora:35-ppc64le uname -m
ppc64le
```

Then I could install clang 12.

```
$ podman run --rm -it registry.fedoraproject.org/fedora:35-ppc64le bash
[root@0b26c2f39c41 /]# dnf install clang

[root@0b26c2f39c41 /]# rpm -q clang
clang-12.0.0-0.7.rc3.fc35.ppc64le

[root@0b26c2f39c41 /]# clang --version
clang version 12.0.0 (Fedora 12.0.0-0.7.rc3.fc35)
Target: powerpc64le-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

If you like, I can contribute this case to one of this repo's CIs.

**Comment by junaruga** [comment]
> I don't suppose you know an easier way to test than installing a VM and running it in qemu?

Ah sorry I misunderstood your comment. Yeah, what I know is only running VM in qemu...

**Comment by junaruga** [comment]
Ah I think if you have ppc64le hardware, you can just run the VM without qemu like this.

```
$ docker run --rm -t registry.fedoraproject.org/fedora:35 uname -m
```

or 

```
$ docker run --rm -t registry.fedoraproject.org/fedora:35-ppc64le uname -m
```

**Comment by nemequ** [comment]
Awesome, thanks! I was actually able to skip most of this since I could use ppc64le hardware; just had to use `registry.fedoraproject.org/fedora:35-ppc64le` instead of `fedora:35`.  I was able to confirm that it's a libc++ issue:

```
[root@d7b05e55a726 ~]# cat test.cpp 
#include <complex>

int main(void) { return 0; }

[root@d7b05e55a726 ~]# clang -o test test.cpp
In file included from test.cpp:1:
In file included from /usr/lib/gcc/ppc64le-redhat-linux/11/../../../../include/c++/11/complex:45:
In file included from /usr/lib/gcc/ppc64le-redhat-linux/11/../../../../include/c++/11/sstream:38:
In file included from /usr/lib/gcc/ppc64le-redhat-linux/11/../../../../include/c++/11/istream:38:
In file included from /usr/lib/gcc/ppc64le-redhat-linux/11/../../../../include/c++/11/ios:40:
In file included from /usr/lib/gcc/ppc64le-redhat-linux/11/../../../../include/c++/11/bits/char_traits.h:39:
In file included from /usr/lib/gcc/ppc64le-redhat-linux/11/../../../../include/c++/11/bits/stl_algobase.h:63:
/usr/lib/gcc/ppc64le-redhat-linux/11/../../../../include/c++/11/ext/numeric_traits.h:222:38: error: __float128 is not supported on this target
    struct __numeric_traits_floating<__ieee128>
                                     ^
/usr/lib/gcc/ppc64le-redhat-linux/11/../../../../include/c++/11/ext/numeric_traits.h:230:29: error: __float128 is not supported on this target
    struct __numeric_traits<__ieee128>
                            ^
/usr/lib/gcc/ppc64le-redhat-linux/11/../../../../include/c++/11/ext/numeric_traits.h:231:40: error: __float128 is not supported on this target
    : public __numeric_traits_floating<__ieee128>
                                       ^
3 errors generated.
[root@d7b05e55a726 ~]# clang --version
clang version 12.0.0 (Fedora 12.0.0-0.7.rc3.fc35)
Target: powerpc64le-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

Debian has binfmt, but I haven't figured out how to get it working from inside a Docker container :(.  I'll have to try it with Fedora.

Anyways, I use Fedora for my desktop, so I'll definitely keep this bookmarked :)

**Comment by junaruga** [comment]
> Debian has binfmt, but I haven't figured out how to get it working from inside a Docker container :(. I'll have to try it with Fedora.

Though I forget I shared you about this, in the past, I had a talk about the qemu-user-static and binfmt_misc in the Fedora event: Flock 2019 (`https://github.com/multiarch/qemu-user-static/issues/90`). My [slide](https://github.com/junaruga/fedora-workshop-multiarch/blob/master/slides/Lets-add-Fedora-multiarch-to-CI.pdf) might be good to know the topic. The binfmt file installed on the host machine also works in the space of container. That's the trick to run different architecture's container.

> Anyways, I use Fedora for my desktop, so I'll definitely keep this bookmarked :)

OK! Thanks for checking it! So, seeing this ticket is closed, you fixed this issue on the master branch, right?

**Comment by nemequ** [comment]
> Though I forget I shared you about this, in the past, I had a talk about the qemu-user-static and binfmt_misc in the Fedora event: Flock 2019 (`https://github.com/multiarch/qemu-user-static/issues/90`). My [slide](https://github.com/junaruga/fedora-workshop-multiarch/blob/master/slides/Lets-add-Fedora-multiarch-to-CI.pdf) might be good to know the topic. The binfmt file installed on the host machine also works in the space of container. That's the trick to run different architecture's container.

Ooohh, I'll have to try that.  Thanks for sharing!

This also showed me how I can get recent gcc/clang versions installed on s/390x (the VM I have access to is running RHEL 8), so I should be able to start working on #733 right away ☺

> OK! Thanks for checking it! So, seeing this ticket is closed, you fixed this issue on the master branch, right?

No, sorry but I don't think there is anything I can do.  AFAIK there is nothing we can do to work around <complex> in C++ (we can, and do, avoid <complex.h> in C, but the same tricks don't work in C++).  If you (or anyone else) wants to try, the revelant code is in [simde/simde-complex.h](https://github.com/simd-everywhere/simde/blob/master/simde/simde-complex.h).  I'd be *really* happy to accept a patch which allows us to avoid <complex>, even if only on some compilers.

You could [use LLVM's libc++](https://libcxx.llvm.org/docs/UsingLibcxx.html#getting-started) (add `-stdlib=libc++` to CXXFLAGS), I think that would do the trick.  You may also want to report the issue upstream; just including `<complex>` triggers it so I have a feeling it will get addressed pretty quickly.

I don't mind leaving this open to track any upstream issues.

**Comment by junaruga** [comment]
> This also showed me how I can get recent gcc/clang versions installed on s/390x (the VM I have access to is running RHEL 8), so I should be able to start working on #733 right away

That's nice. It's really great if we can use the s/390x machine too as CI running machine with Cirrus CI.

> You could use LLVM's libc++ (add -stdlib=libc++ to CXXFLAGS), I think that would do the trick. You may also want to report the issue upstream; just including <complex> triggers it so I have a feeling it will get addressed pretty quickly.

Let me try something. Does this issue comes from the libc++ in clang-12, right? The upstream to report is the clang project?

> I don't mind leaving this open to track any upstream issues.

I am okay to close this ticket for now. :)

**Comment by nemequ** [comment]
> > This also showed me how I can get recent gcc/clang versions installed on s/390x (the VM I have access to is running RHEL 8), so I should be able to start working on #733 right away
> 
> That's nice. It's really great if we can use the s/390x machine too as CI running machine with Cirrus CI.

Unfortunately the s/390x VM is temporary; it's [a free trial](https://developer.ibm.com/components/ibm-linuxone/gettingstarted/).
 
> > You could use LLVM's libc++ (add -stdlib=libc++ to CXXFLAGS), I think that would do the trick. You may also want to report the issue upstream; just including  triggers it so I have a feeling it will get addressed pretty quickly.
> 
> Let me try something. Does this issue comes from the libc++ in clang-12, right? The upstream to report is the clang project?

I think the problem is the GNU C++ Library (which I believe is in the GCC source tree); the work-around would be to use LLVM's C++ library instead.

**Comment by junaruga** [comment]
> Unfortunately the s/390x VM is temporary; it's a free trial.

Ah okay.

> I think the problem is the GNU C++ Library (which I believe is in the GCC source tree); the work-around would be to use LLVM's C++ library instead.

>  I was able to confirm that it's a libc++ issue:

```
$ find /usr/include/ -name complex.h
/usr/include/complex.h
/usr/include/c++/10/tr1/complex.h
/usr/include/c++/10/complex.h

$ rpm -qf /usr/include/complex.h
glibc-headers-x86-2.32-4.fc33.noarch

$ rpm -qf /usr/include/c++/10/tr1/complex.h
libstdc++-devel-10.2.1-9.fc33.x86_64

$ rpm -qf /usr/include/c++/10/complex.h
libstdc++-devel-10.2.1-9.fc33.x86_64
```

I can see the `/usr/include/complex.h` file comes from  the `glibc-headers` RPM sub package in the glibc RPM package, and the other `comlex.h` files come from `libstdc++-devel` sub package in the gcc RPM package on my Fedora 33.

So, maybe I will try to report it with a small reproducer to the Fedora glibc issue ticket [1] or the GNU libc upstream project [2] at first. If it is not a proper, maybe ask it on Fedora gcc [3] or the gcc upstream project [4].

[1] https://src.fedoraproject.org/rpms/glibc
[2] http://www.gnu.org/software/libc/

[3] https://src.fedoraproject.org/rpms/gcc/
[4] http://gcc.gnu.org

**Comment by nemequ** [comment]
That makes sense to me; someone working on the glibc packaging would likely know where to redirect the report to even if glibc isn't the right place.

**Comment by junaruga** [comment]
@nemequ When building on the commit: `22609d4661340098a17bddb9b3a7b8b18680079a` that is 3 commits before HEAD, I find this ninja build error does not happen any more. Did you do something to fix?

Here is the build and test log.

```
=== 2.1. tests on clang without flags ===
+ BUILD_DIR=build/clang
+ CC=clang
+ CXX=clang++
+ _setup
+ meson setup build/clang
The Meson build system
Version: 0.57.1
Source dir: /builddir/build/BUILD/simde-22609d4661340098a17bddb9b3a7b8b18680079a
Build dir: /builddir/build/BUILD/simde-22609d4661340098a17bddb9b3a7b8b18680079a/build/clang
Build type: native build
Project name: SIMDe
Project version: 0.7.3
C compiler for the host machine: clang (clang 12.0.0 "clang version 12.0.0 (Fedora 12.0.0-0.7.rc3.fc35)")
C linker for the host machine: clang ld.bfd 2.36.1-8
C++ compiler for the host machine: clang++ (clang 12.0.0 "clang version 12.0.0 (Fedora 12.0.0-0.7.rc3.fc35)")
C++ linker for the host machine: clang++ ld.bfd 2.36.1-8
Host machine cpu family: ppc64
Host machine cpu: ppc64le
Library m found: YES
Compiler for C supports arguments -fopenmp-simd: YES 
Compiler for C++ supports arguments -fopenmp-simd: YES 
Compiler for C supports arguments -Wpsabi: YES 
Compiler for C++ supports arguments -Wpsabi: YES 
Library m found: YES
Build targets in project: 1090
Found ninja-1.10.2 at /usr/bin/ninja
+ _build
+ rm -f build.log
+ _time ninja -C build/clang -v -j 8
+ head -4 build.log
+ /usr/bin/time -f '=> [%E]' ninja -C build/clang -v -j 8
ninja: Entering directory `build/clang'
[1/2180] clang -Itest/common/common-c.p -Itest/common -I../../test/common -I. -I../.. -Xclang -fcolor-diagnostics -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c99 -g -fopenmp-simd -DSIMDE_ENABLE_OPENMP -Wno-psabi -DSIMDE_TEST_BARE -MD -MQ test/common/common-c.p/common.c.o -MF test/common/common-c.p/common.c.o.d -o test/common/common-c.p/common.c.o -c ../../test/common/common.c
[2/2180] clang  -o test/common/common-c test/common/common-c.p/common.c.o -Wl,--as-needed -Wl,--no-undefined -Wl,--start-group -lm -Wl,--end-group
+ tail -3 build.log
6 warnings generated.
[2180/2180] clang++  -o test/wasm/xor-native-cpp test/wasm/xor-native-cpp.p/meson-generated_.._xor.cpp.o -Wl,--as-needed -Wl,--no-undefined -Wl,--start-group -lm -Wl,--end-group
=> [5:19.10]
+ _test
+ _time meson test -C build/clang -q --no-rebuild --print-errorlogs
+ /usr/bin/time -f '=> [%E]' meson test -C build/clang -q --no-rebuild --print-errorlogs
Ok:                 1090
Expected Fail:      0   
Fail:               0   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0   
Full log written to /builddir/build/BUILD/simde-22609d4661340098a17bddb9b3a7b8b18680079a/build/clang/meson-logs/testlog.txt
=> [0:06.48]
```

**Comment by junaruga** [comment]
Now I tested with [the testing RPM spec file (recipe file)](https://github.com/junaruga/report-clang-12-ppc64le-build-error). And I do not see any error any more. The clang version `Fedora 12.0.0-0.7.rc3.fc35` is same.

```
cat > test.cpp <<EOF
#include <complex.h>
int main(void) {
    return 0;
}
EOF
```

```
+ clang --version
clang version 12.0.0 (Fedora 12.0.0-0.7.rc3.fc35)
Target: powerpc64le-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

+ clang++ --version
clang version 12.0.0 (Fedora 12.0.0-0.7.rc3.fc35)
Target: powerpc64le-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

++ find /usr/include/ -name complex.h
+ for file in $(find /usr/include/ -name complex.h)
+ rpm -qf /usr/include/c++/11/complex.h
libstdc++-devel-11.0.1-0.3.fc35.ppc64le
+ for file in $(find /usr/include/ -name complex.h)
+ rpm -qf /usr/include/c++/11/tr1/complex.h
libstdc++-devel-11.0.1-0.3.fc35.ppc64le
+ for file in $(find /usr/include/ -name complex.h)
+ rpm -qf /usr/include/complex.h
glibc-devel-2.33.9000-2.fc35.ppc64le

+ clang -o test test.cpp
+ clang++ -o test_cpp test.cpp
```

---

Here is the way to comfirm on the Fedora build system just in case.

```
$ git clone https://github.com/junaruga/report-clang-12-ppc64le-build-error.git
$ cd report-clang-12-ppc64le-build-error
$ fedpkg --release rawhide srpm
$ koji build --scratch --nowait --arch-override=ppc64le rawhide *.rpm
```

**Comment by junaruga** [comment]
Can you still see your environment where you saw this build error?
On the current Fedora rawhide (=35) environment, I see the `libstdc++-devel-11.0.1-0.3.fc35.ppc64le
` and `glibc-devel-2.33.9000-2.fc35.ppc64le`. But I guess the version triggered might be `libstdc++-devel-11.0.1-0.1.fc35.ppc64le` seeing [the gcc.spec changelog dates](https://src.fedoraproject.org/rpms/gcc/blob/rawhide/f/gcc.spec#_3129) including `libstdc++devel`. I think the `glibc-devel` is not changed since we saw the error seeing [the glibc changelog date](https://src.fedoraproject.org/rpms/glibc/blob/rawhide/f/glibc.spec#_2292).

```
+ rpm -qf /usr/include/c++/11/complex.h
libstdc++-devel-11.0.1-0.3.fc35.ppc64le

+ rpm -qf /usr/include/c++/11/tr1/complex.h
libstdc++-devel-11.0.1-0.3.fc35.ppc64le

+ rpm -qf /usr/include/complex.h
glibc-devel-2.33.9000-2.fc35.ppc64le
```

**Comment by nemequ** [comment]
I was just using a F35 container on ppc64le hardware (running debian unstable; I can give you access if you want).  But yes, it looks like the issue has been resolved; I can no longer reproduce this on a new container.

**Comment by junaruga** [comment]
@nemequ that's okay. I do not need to have the access. Thanks!
