### ISSUE TITLE
WebAssembly functions

### ISSUE THREAD

**Issue by nemequ** [simd-everywhere/simde#76]
Here is the current API: https://github.com/emscripten-core/emscripten/blob/master/system/include/wasm_simd128.h

Since this is pretty new and not a lot of code is targeting it, for now it's probably more important to get other ISA extensions accelerated *using* these than to create a portable implementation of them.  That said, it would be helpful for people targeting WASM to be able to compile and test code using native tools.

It could also be interesting as a common layer we could call from all ISA extensions and avoid some duplication.

**Comment by ngzhian** [comment]
Hi Evan. I work on SIMD in WebAssembly, and will be interested to discuss this more.

Do you have an idea of how this will look like? I haven't dug into simde much at all, and I imagine a possible way of implementing this will be to take a simde header file, like sse2.h, add a new #ifdef for WASM, and inside of those #ifdefs call into the intrinsics in wasm_simd128.h?

**Comment by nemequ** [comment]
That's not what this issue is about, but it's also something which needs to be done.  This issue is about creating functions in SIMDe which look like the ones from WASM; for example a `simde_wasm_i8x16_add` which works even when you're not targeting WASM, or are targeting WASM without SIMD.

This issue is useful for people who want to write code which will work on WASM while still compiling for their native platform, which tends to be faster and have good debugging tools.  WASM could also be a nice common layer to target for people who want to write portable applications; it should be possible to have good implementations of these functions on SSE, NEON, AltiVec, etc. since it was designed as kind of a lowest-common denominator.  The only drawback to that is that the API depends on aliasing like Intel's instead of a nice clean API like NEON has :(

I just opened up #86 to discuss what you're talking about, but basically yes, if that's your goal then that's what you need to do.  If you want I'd be happy to take care of the first function or two in SSE to get things started, then you would have an example to look at for the rest.  Let's talk in #86 :)
