### ISSUE TITLE
sse2.h failing on ARMv7 with `vcvtnq` missing

### ISSUE THREAD

**Issue by jpcima** [simd-everywhere/simde#768]
Hi, I've got a report of failure with clang-11 ARM.
https://github.com/sfztools/sfizz/issues/890#issuecomment-835805672

When I have a deeper look in clang 11's intrinsic headers, I notice `vcvtnq_s32_f32` to be declared under the conditional `__ARM_ARCH >= 8`.

On the other hand, SIMDe is checking for ARM32 V7.
https://github.com/simd-everywhere/simde/blob/dc215cde6731adeba33fdceb32710b3cfdd00c24/simde/x86/sse2.h#L2632-L2633

**Comment by nemequ** [comment]
Oops, thanks!

Looks like CI missed this since we don't have a -ffast-math build :(.  I'll try to look into adding one, but Drone is already a bit overloaded right now so I'm not sure it's going to happen…

Should be fixed soon, just need to wait on CI to do its thing.
