### ISSUE TITLE
Start planning for 0.8 or 1.0 release

### ISSUE THREAD

**Issue by mr-c** [simd-everywhere/simde#861]
I would like to there to be a new SIMDe release once Debian Bullseye is released

>  517 changed files with 219,189 additions and 13,853 deletions. 

https://github.com/simd-everywhere/simde/compare/v0.7.2...master

**Comment by nemequ** [comment]
I was thinking about putting out a 0.8.0 after GSoC is done; development will probably slow down significantly then.

Eventually I'm thinking it might be a good idea to move to a time-based release schedule.

**Comment by junaruga** [comment]
This means that next release version is not 0.7.3 but 0.8 or 1.0, while currently 0.7.3 is actually set? https://github.com/simd-everywhere/simde/commit/36b65e3ea33776accda8cd316e6324ae9d0a9113

**Comment by mr-c** [comment]
@junaruga Correct. The odd 0.0.x releases are development versions, not public releases.

**Comment by junaruga** [comment]
OK!

**Comment by mr-c** [comment]
Debian Bullseye has been released! I've uploaded a snapshot of today's SIMDe to Debian Experimental:  https://tracker.debian.org/news/1247389/accepted-simde-0730git202108141910103f186a0-1-source-into-experimental/

I just found https://github.com/simd-everywhere/simde/issues/901 , so I've disabled testing with clang on amd64 for the moment; the rest of the builds will be visible at https://buildd.debian.org/status/package.php?p=simde&suite=experimental

**Comment by mr-c** [comment]
I did another snapshot build today: https://buildd.debian.org/status/package.php?p=simde&suite=experimental is of https://github.com/simd-everywhere/simde/commit/90523a281a67a50b0892364bc35f37a5fbfb7479

Mostly GCC 11.2, some clang testing as well
`dpbf16` is skipped on i686

https://salsa.debian.org/med-team/simde/-/blob/ca088f16e02a1ddf3a7194bf8610cbe0c0f28a05/debian/rules

**Comment by mr-c** [comment]
I did a new build + test on all of the Debian architectures (official and unofficial) and unfortunately we've got test failures;

assistance in tracking these down would be appreciated ( @wrv  are you available? )

https://buildd.debian.org/status/package.php?p=simde&suite=experimental

**Comment by wrv** [comment]
Yes, I can help!

**Comment by mr-c** [comment]
Thank you @wrv ; some of the differences are likely due to the extra default compiler options used by Debian. I guess we should add those to the CI to catch things sooner :-)

Here are the extra flags on i386/i686: `-O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2`

**Comment by mr-c** [comment]
Ah, i686 was being tested on CircleCI; testing with docker shows 292 test failures ; yet [Debian's i686 build only had 22 failures](https://buildd.debian.org/status/fetch.php?pkg=simde&arch=i386&ver=0.7.3%7E0git20230118123246.d1e75cd-1&stamp=1674059976&raw=0)  (likely to be the result of only a few lines wrong); maybe the `-O2` optimized out some wrong paths?

**Comment by mr-c** [comment]
Update from the Debian Med Sprint,

I've built an experimental package of the latest SIMDe code and I'm using it to rebuild over 25 tools across all the Debian architectures. If there are no regressions, then I'll make a 0.7.4 release

[The build status with SIMDe 0.7.2](https://buildd.debian.org/status/package.php?p=examl%2Clast-align%2Cpython-skbio%2Cminimap2%2Cpbcopper%2Chisat2%2Cfermi-lite%2Cbowtie2%2Cbwa%2Craxml%2Ckalign%2Cfasta3%2Cplink2%2Cmmseqs2%2Cspoa%2Cwtdbg2%2Ckmc%2Chhsuite%2Cabpoa%2Crna-star%2Cparasail%2Cngmlr%2Cseqan-raptor%2Crapmap%2Csnap-aligner%2Cscrappie&suite=sid) 

[and with the latest dev version of SIMDe](https://buildd.debian.org/status/package.php?p=examl%2Clast-align%2Cpython-skbio%2Cminimap2%2Cpbcopper%2Chisat2%2Cfermi-lite%2Cbowtie2%2Cbwa%2Craxml%2Ckalign%2Cfasta3%2Cplink2%2Cmmseqs2%2Cspoa%2Ckmc%2Chhsuite%2Cabpoa%2Crna-star%2Cparasail%2Cngmlr%2Cseqan-raptor%2Crapmap%2Csnap-aligner%2Cscrappie&suite=experimental)

If there are squares on the second link that are red where they are green on the first link, then there is a regression. (Give it a day or two for the builders to catch up)

**Comment by mr-c** [comment]
Update from the Debian Med Sprint,

I've built an experimental package of the latest SIMDe code and I'm using it to rebuild over 25 tools across all the Debian architectures. If there are no regressions, then I'll make a 0.7.4 release

[The build status with SIMDe 0.7.2](https://buildd.debian.org/status/package.php?p=examl%2Clast-align%2Cpython-skbio%2Cminimap2%2Cpbcopper%2Chisat2%2Cfermi-lite%2Cbowtie2%2Cbwa%2Craxml%2Ckalign%2Cfasta3%2Cplink2%2Cmmseqs2%2Cspoa%2Cwtdbg2%2Ckmc%2Chhsuite%2Cabpoa%2Crna-star%2Cparasail%2Cngmlr%2Cseqan-raptor%2Crapmap%2Csnap-aligner%2Cscrappie&suite=sid) 

[and with the latest dev version of SIMDe](https://buildd.debian.org/status/package.php?p=examl%2Clast-align%2Cpython-skbio%2Cminimap2%2Cpbcopper%2Chisat2%2Cfermi-lite%2Cbowtie2%2Cbwa%2Craxml%2Ckalign%2Cfasta3%2Cplink2%2Cmmseqs2%2Cspoa%2Ckmc%2Chhsuite%2Cabpoa%2Crna-star%2Cparasail%2Cngmlr%2Cseqan-raptor%2Crapmap%2Csnap-aligner%2Cscrappie&suite=experimental)

If there are squares on the second link that are red where they are green on the first link, then there is a regression. Only the first 9 architectures are officially supported in Debian, so don't worry about `alpha` and onward.

(Give it a day or two for the builders to catch up)

**Comment by wrv** [comment]
How do you recommend I setup my local machine for testing these issues? Is it all in the [docker/](https://github.com/simd-everywhere/simde/tree/master/docker) directory?

**Comment by mr-c** [comment]
> How do you recommend I setup my local machine for testing these issues? Is it all in the [docker/](https://github.com/simd-everywhere/simde/tree/master/docker) directory?

Yeah, that's the easiest way for compilers that you don't have native system packages for.

I run it with `PERSISTENT_BUILD_DIR=$PWD/build ./simde-dev.sh` to save the build tree between invocation.

FYI, I'm going to make a 0.7.4 release, as the test builds with the Debian packages all passed; see https://github.com/simd-everywhere/simde/issues/983

Fixes for the other outstanding issues (especially clang) are very much still welcome!
