### ISSUE TITLE
gcc 4.9.2 - armv7 neon - simde_mm_unpacklo_epi64 give error about wrong argument type for vget_low_s64

### ISSUE THREAD

**Issue by Cadichon** [simd-everywhere/simde#896]
I tryed to compile some code that uses SSE2 instructions for ARMv7 using gcc 4.9.2 (linaro-1.13.1-4.9-2014.09) and SIMDE release amalgamed-0.7.2.
The compiler gave me an error inside the simde_mm_unpacklo_epi64 function, saying that the wrong type of argument was passed to vget_low_s64 (line 21624 of x86/sse2.h) :
```
C:/XXX/include/simde/x86/sse2.h: In function 'simde__m128i simde_mm_unpacklo_epi64(simde__m128i, simde__m128i)':
C:/XXX/include/simde/x86/sse2.h:21624:42: note: use -flax-vector-conversions to permit conversions between vectors with differing element types or numbers of subparts
       int64x1_t a_l = vget_low_s64(a_.i64);
                                          ^
C:/XXX/include/simde/x86/sse2.h:21624:42: error: cannot convert '__vector(2) long long int' to 'int64x2_t {aka __vector(2) __builtin_neon_di}' for argument '1' to 'int64x1_t vget_low_s64(int64x2_t)'
```
After looking at the code :
```c++
#if defined(SIMDE_ARM_NEON_A32V7_NATIVE)
  int64x1_t a_l = vget_low_s64(a_.i64);
  int64x1_t b_l = vget_low_s64(b_.i64);
  r_.neon_i64 = vcombine_s64(a_l, b_l);
```
it seems that both vget_low_s64 should take a_.neon_i64 and b_.neon_i64 instead of a_.i64 and b_.i64 respectively

**Comment by nemequ** [comment]
Thanks for the report.  This has been fixed (by b5fbe398a87b0138f1d636c3e69c9325689772b0) in git for quite a while (along with numerous other fixes and improvements) and will be part of the next release, so the easiest solution would probably be to upgrade.

The amalgamated headers are automatically built and deployed for each commit, so you can always download a copy of the latest version:

 * [neon](https://simde.netlify.com/amalgamated/arm/neon.h)
 * [sve](https://simde.netlify.com/amalgamated/arm/sve.h)
 * [msa](https://simde.netlify.com/amalgamated/mips/msa.h)
 * [relaxed-simd](https://simde.netlify.com/amalgamated/wasm/relaxed-simd.h)
 * [simd128](https://simde.netlify.com/amalgamated/wasm/simd128.h)
 * [avx2](https://simde.netlify.com/amalgamated/x86/avx2.h)
 * [avx512](https://simde.netlify.com/amalgamated/x86/avx512.h)
 * [avx](https://simde.netlify.com/amalgamated/x86/avx.h)
 * [clmul](https://simde.netlify.com/amalgamated/x86/clmul.h)
 * [f16c](https://simde.netlify.com/amalgamated/x86/f16c.h)
 * [fma](https://simde.netlify.com/amalgamated/x86/fma.h)
 * [gfni](https://simde.netlify.com/amalgamated/x86/gfni.h)
 * [mmx](https://simde.netlify.com/amalgamated/x86/mmx.h)
 * [sse2](https://simde.netlify.com/amalgamated/x86/sse2.h)
 * [sse3](https://simde.netlify.com/amalgamated/x86/sse3.h)
 * [sse4.1](https://simde.netlify.com/amalgamated/x86/sse4.1.h)
 * [sse4.2](https://simde.netlify.com/amalgamated/x86/sse4.2.h)
 * [sse](https://simde.netlify.com/amalgamated/x86/sse.h)
 * [ssse3](https://simde.netlify.com/amalgamated/x86/ssse3.h)
 * [svml](https://simde.netlify.com/amalgamated/x86/svml.h)
 * [xop](https://simde.netlify.com/amalgamated/x86/xop.h)
