### ISSUE TITLE
Compile failures with `-fno-lax-vector-conversions`

### ISSUE THREAD

**Issue by ngzhian** [simd-everywhere/simde#898]
Command: `clang simde/arm/neon/qsub.h  -Werror -O0 -Wno-c++11-narrowing -I.`

Seems like there is an issue here:
https://github.com/simd-everywhere/simde/blob/master/simde/arm/neon/qsub.h#L331

```
simde/arm/neon/qsub.h:331:17: error: cannot convert between vector type '__attribute__((__vector_size__(2 * sizeof(int)))) int' (vector of 2 'int' values) and vector type '__attribute__((__vector_size__(2 * sizeof(uint32_t)))) uint32_t' (vector of 2 'uint32_t' values) as implicit conversion would cause truncation
      r_.values &= (r_.values <= a_.values);
                ^
simde/arm/neon/qsub.h:360:17: error: cannot convert between vector type '__attribute__((__vector_size__(1 * sizeof(long long)))) long long' (vector of 1 'long long' value) and vector type '__attribute__((__vector_size__(1 * sizeof(uint64_t)))) uint64_t' (vector of 1 'uint64_t' value) as implicit conversion would cause truncation
      r_.values &= (r_.values <= a_.values);
                ^
simde/arm/neon/qsub.h:666:17: error: cannot convert between vector type '__attribute__((__vector_size__(2 * sizeof(long long)))) long long' (vector of 2 'long long' values) and vector type '__attribute__((__vector_size__(2 * sizeof(uint64_t)))) uint64_t' (vector of 2 'uint64_t' values) as implicit conversion would cause truncation
      r_.values &= (r_.values <= a_.values);
```

Do we need a reinterpret cast here?

**Comment by ngzhian** [comment]
I would like to reopen this, I found more compilation issues in simde_vcvtq_u64_f64:

```
arm_neon.h:30267:99: error: cannot convert between vector type '__attribute__((__vector_size__(2 * sizeof(const double)))) const double' (vector of 2 'const double' values) and vector type '__
attribute__((__vector_size__(2 * sizeof(simde_float64)))) simde_float64' (vector of 2 'simde_float64' values) as implicit conversion would cause truncation
      int64_t max_mask SIMDE_VECTOR(16) = HEDLEY_REINTERPRET_CAST(__typeof__(max_mask), a_.values > max_representable)
```

I also have a small repro case here: https://godbolt.org/z/7zfvYavGv

The "fix" seems to be adding a const? Is this a bug in the compiler?

**Comment by ngzhian** [comment]
How do you feel about removing "const" from the various constants so that I can get this into Emscripten first, It doesn't feel like a good fix, but it can unblock merging into Emscripten. I can also add a comment referring to this bug in all those places. (IIRC there's not a lot of them, maybe ~8 functions in total.)

**Comment by nemequ** [comment]
No need.  After a bit of playing around, I figured out that the problem only occurs when the vectors are declared like this:

```c
const int32_t v __attribute__((__vector_size__(16)));
```

Instead of;

```c
const int32_t __attribute__((__vector_size__(16))) v;
```

So if we just move the `SIMDE_VECTOR(x)` to *before* the name it works as intended everywhere.

**Comment by nemequ** [comment]
I fixed most of these issues over the weekend with what is in staging right now.  There are still some failures on drone (arm), but I'll try to resolve those soon

**Comment by nemequ** [comment]
Done.
