### ISSUE TITLE
simde_mm_slli_epi32 behaviour different between intel and arm

### ISSUE THREAD

**Issue by FigBug** [simd-everywhere/simde#905]
On Intel, 2nd parameter may be a variable, on arm it must be a constant.

**Comment by mr-c** [comment]
Thanks @baconpaul ; do the tests still pass with that change? If so, could you send a PR with additional test data that demonstrates the correctness?

**Comment by baconpaul** [comment]
OK running brew install meson right now :)

**Comment by baconpaul** [comment]
OK a PR change in which seems to fix the problem.

**Comment by aqrit** [comment]
> __m128i _mm_slli_epi32 (__m128i a, int **imm8**)

`pslld` requires an 8-bit immediate.

If you use it incorrectly...
some compiler (but not all) will convert it to a `_mm_sll_epi32(a, _mm_cvtsi32_si128(b))` (or similar).

**Comment by aqrit** [comment]
I don't think simde could provide a portable "fix" for this without introducing performance regressions.

**Comment by baconpaul** [comment]
Oh thank you! So the error is mine not simde. I appreciate it. I'll close my PR.

**Comment by baconpaul** [comment]
Also yes clearly the library shouldn't fix a problem which is a usage problem.
