### ISSUE TITLE
Missing HEDLEY_DIAGNOSTIC_POP

### ISSUE THREAD

**Issue by Shaac** [simd-everywhere/simde#910]
Hello,

There is a [HEDLEY_DIAGNOSTIC_PUSH](https://github.com/simd-everywhere/simde/blob/master/simde/x86/sse.h#L4474) without a corresponding `HEDLEY_DIAGNOSTIC_POP` in x86/sse.h, just before `simde_mm_unpackhi_ps` function.

This leads to warning C5032 in MSVC.

I’d open a PR myself to fix add the missing POP, but I’m not sure where it should go. I guess after `simde_mm_unpackhi_ps` declaration.

**Comment by mr-c** [comment]
I started on this in https://github.com/simd-everywhere/simde/commit/09fc0b8f355d939bacb25ddeb461d894dca4cf11 ; but it uncovered more issues than I have time to fix right now
