### ISSUE TITLE
[NEON] warning: redefinition of typedef 'float16_t' is a C11 feature [-Wtypedef-redefinition]

### ISSUE THREAD

**Issue by dgazzoni** [simd-everywhere/simde#911]
Consider the following, essentially empty, file:

```
#define SIMDE_ENABLE_NATIVE_ALIASES
#include "arm/neon.h"

int main() {
    return 0;
}
```

Compiling this with Apple's clang version using the `-std=gnu99` flag produces the following compilation error:

```
.../arm/neon/types.h:941:33: warning: redefinition of typedef 'float16_t' is a C11 feature [-Wtypedef-redefinition]
  typedef   simde_float16_t     float16_t;
                                ^
.../arm/neon/types.h:857:33: note: previous definition is here
  typedef   simde_float16_t     float16_t;
```

Header files are obtained from the `647dc12` commit. A pull request will soon follow.

**Comment by mr-c** [comment]
This was fixed in https://github.com/simd-everywhere/simde/commit/7f40f35685cf509f3a47988f714bc54d7663743b
