### ISSUE TITLE
Version 0.7.3 is not tagged

### ISSUE THREAD

**Issue by yurivict** [simd-everywhere/simde#917]
This slows down its adoption because it isn't being discovered by new version discovery systems.

**Comment by mr-c** [comment]
Hello @yurivict 0.7.3 just means we're in between releases. The next release after 0.7.2 will be 0.7.4 or 0.8.0 see https://github.com/simd-everywhere/simde/milestone/1 and https://github.com/simd-everywhere/simde/issues/861
