### ISSUE TITLE
Is `simde_mm512_load_ps` missing?

### ISSUE THREAD

**Issue by lkskstlr** [simd-everywhere/simde#930]
Hi,

thank you very much for this cool library.

I noticed that `simde_mm512_load_ps` is missing while `simde_mm512_loadu_ps` is implemented. However, both seem to exist for Intel intrinsics (see screenshot). Maybe I oversaw one or maybe they do the same anyways?

Thanks
Lukas

![Screenshot from 2021-10-25 13-28-29](https://user-images.githubusercontent.com/14993470/138687358-aa6b531e-bdcb-4ca3-8861-ffadb6f857f5.png)

**Comment by mr-c** [comment]
This was fixed in https://github.com/simd-everywhere/simde/commit/d5880491cc07564a01f840b580d59701a51bb082
