### ISSUE TITLE
simde/x86/avx512/permutex2var.h fails to compile on Visual C++

### ISSUE THREAD

**Issue by johnplatts** [simd-everywhere/simde#950]
The following lines of code in lines 706, 707, 1181, and 1182 simde/x86/avx512/permutex2var.h give compiler errors in Visual C++:
```
    lo = HEDLEY_REINTERPRET_CAST(__typeof__(lo), _mm256_blend_epi16(_mm256_slli_epi32(hilo2, 16), hilo, 0x55));
    hi = HEDLEY_REINTERPRET_CAST(__typeof__(hi), _mm256_blend_epi16(hilo2, _mm256_srli_epi32(hilo, 16), 0x55));
```

The lines of code can be fixed as follows:
```
    lo = _mm256_blend_epi16(_mm256_slli_epi32(hilo2, 16), hilo, 0x55);
    hi = _mm256_blend_epi16(hilo2, _mm256_srli_epi32(hilo, 16), 0x55);
```

The HEDLEY_REINTERPRET_CAST is unnecessary in lines 706, 707, 1181, and 1182 of the simde/x86/avx512/permutex2var.h header since the _mm256_blend_epi16 function already returns a __m256i result and the type of both lo and hi are __m256i types.

**Comment by rosbif** [comment]
I wrote most of permutex2var but I don't remember these casts.
Looking at the history it seems that Evan added these casts because old versions of clang had an incorrect definition of _mm256_blend_epi16.
As I don't know any more details I shall let Evan look at it.
However I am rather surprised that an unnecessary cast generates an error.
Is it a real error or a warning promoted to an error with -Werror?

**Comment by johnplatts** [comment]
> 

The error that I am getting when simde/x86/avx512/permutex2var.h is included in Visual C++ is an hard error due to Visual C++ not supporting the __typeof__ operator.

The error does not occur when the -arch:AVX512 option is specified.

**Comment by nemequ** [comment]
Yeah, it's a GNU extension and not supported by MSVC (MSVC and IAR are the only compilers I am aware of that don't support it at this point).  Just replacing it with the hard-coded type we want (`__m256i` in this case) is probably best.

> The HEDLEY_REINTERPRET_CAST is unnecessary in lines 706, 707, 1181, and 1182 of the simde/x86/avx512/permutex2var.h header since the _mm256_blend_epi16 function already returns a __m256i result and the type of both lo and hi are __m256i types.

Unfortunately they are necessary... older versions of clang ([prior to 3.7.0](https://github.com/llvm/llvm-project/commit/b929ad7b1726a32650a8051f69a747fb6836c540)) implement `_mm256_blend_epi16` with an incorrect signature, without the cast.  We could make it conditional (based on the `SIMDE_BUG_CLANG_REV_234560` macro), but *correctly* doing the cast everywhere shouldn't be a problem.

**Comment by johnplatts** [comment]
I opened a new issue (issue https://github.com/simd-everywhere/simde/issues/952) as commit https://github.com/simd-everywhere/simde/commit/88931164bdb8b628702079bfa177087a614cc975 does not resolve the issue in C++ mode in Visual C++ with the -arch:AVX2 flag as Visual C++ does not allow a reinterpret_cast conversion from a __m256i to a __m256i.
