### ISSUE TITLE
Change !defined(SIMDE_X86_SSE4_1_NATIVE) to !defined(SIMDE_X86_SSE4_2_NATIVE) in line 186 of simde/simde-features.h

### ISSUE THREAD

**Issue by johnplatts** [simd-everywhere/simde#955]
Here are lines 186-188 of simde/simde-features.h:
```
#if defined(SIMDE_X86_AVX_NATIVE) && !defined(SIMDE_X86_SSE4_1_NATIVE)
  #define SIMDE_X86_SSE4_2_NATIVE
#endif
```

Here is how lines 186-188 of simde/simde-features.h should read:
```
#if defined(SIMDE_X86_AVX_NATIVE) && !defined(SIMDE_X86_SSE4_2_NATIVE)
  #define SIMDE_X86_SSE4_2_NATIVE
#endif
```

Note that !defined(SIMDE_X86_SSE4_1_NATIVE) should be changed to !defined(SIMDE_X86_SSE4_2_NATIVE) in line 186 of simde/simde-features.h.

**Comment by mr-c** [comment]
Thank you @johnplatts ; I'm testing this fix. In the future, please feel free to send a pull request; for small changes like this you  can even click the :pencil: icon to edit directly in the web interface: 

https://github.com/simd-everywhere/simde/blob/master/simde/simde-features.h

![image](https://user-images.githubusercontent.com/1330696/213249841-92ddd1fb-59c2-4f89-ac6f-ea95b13ad3d2.png)
