### ISSUE TITLE
Timeframe for a new release

### ISSUE THREAD

**Issue by jcarpent** [simd-everywhere/simde#959]
Dear developpers,

Thanks a lot for this pretty useful library.
I would like to add simde to conda-forge. Would you have in mind a date for a future release?
It would be nice to provide one of the latest available version of simde within conda, as the latest release is more than one-year old.

Thanks in advance for your feedback,
Best,

Justin

**Comment by jcarpent** [comment]
Dear developpers,

Any news on this issue?
Thanks in advance,

Justin

**Comment by jcarpent** [comment]
@mr-c Kind reminders for this question.
Having a fresh release will help in the development of software rooted in SIMDE.

**Comment by mr-c** [comment]
I'll be working towards a release this weekend as part of the Debian-Med spirit https://wiki.debian.org/Sprints/2022/Debian%20Med%20Sprint%202023%2C%20Berlin

**Comment by jcarpent** [comment]
Thanks a lot @mr-c for this update.
Have a nice weekend.

**Comment by mr-c** [comment]
I anticipate releasing this weekend

**Comment by jcarpent** [comment]
Super ! Thanks a lot @mr-c

**Comment by mr-c** [comment]
https://github.com/simd-everywhere/simde/releases/tag/v0.7.4 is released!
