### ISSUE TITLE
simde-related failure on riscv64

### ISSUE THREAD

**Issue by yurivict** [simd-everywhere/simde#962]
The surge-synthesizer project fails to compile on riscv64 with simde-related message:
```
In file included from /wrkdirs/usr/ports/audio/surge-synthesizer-lv2/work/surge-release_1.9.0/src/common/dsp/effect/BBDEnsembleEffect.cpp:16:
In file included from /wrkdirs/usr/ports/audio/surge-synthesizer-lv2/work/surge-release_1.9.0/src/common/dsp/effect/BBDEnsembleEffect.h:22:
In file included from /wrkdirs/usr/ports/audio/surge-synthesizer-lv2/work/surge-release_1.9.0/src/common/dsp/VectorizedSvfFilter.h:3:
In file included from /wrkdirs/usr/ports/audio/surge-synthesizer-lv2/work/surge-release_1.9.0/src/common/vt_dsp/portable_intrinsics.h:4:
In file included from /nxb-bin/usr/lib/clang/14.0.5/include/immintrin.h:21:
/nxb-bin/usr/lib/clang/14.0.5/include/mmintrin.h:71:12: error: use of undeclared identifier '__builtin_ia32_vec_ext_v2si'
    return __builtin_ia32_vec_ext_v2si((__v2si)__m, 0);
           ^
/nxb-bin/usr/lib/clang/14.0.5/include/mmintrin.h:101:1: error: functions that differ only in their return type cannot be overloaded
_mm_cvtm64_si64(__m64 __m)
^
/usr/local/include/simde/x86/mmx.h:681:30: note: expanded from macro '_mm_cvtm64_si64'
#  define _mm_cvtm64_si64(a) simde_mm_cvtm64_si64(a)
                             ^
/usr/local/include/simde/x86/mmx.h:661:1: note: previous definition is here
simde_mm_cvtm64_si64 (simde__m64 a) {
^
```

clang-13
FreeBSD 13.1

**Comment by rosbif** [comment]
This looks to me like a clang problem.
Clang's own mmintrin.h include file uses an undeclared (and possibly unsupported) builtin.
You seem to be using clang-14 includes with clang-13 : could this be the problem?

**Comment by yurivict** [comment]
> You seem to be using clang-14 includes with clang-13 : could this be the problem?

No, this is my mistake. clang-14 is installed on this machine.

**Comment by yurivict** [comment]
Now I see that this is a surge-synthesizer bug that they include simde on riscv64 architecture.

Sorry for bothering you!

**Comment by rosbif** [comment]
Nevertheless even if riscv64 isn't really supported I think that SIMDe should fall back to portable (generic) code.
I don't see why SIMDe should think that it is being compiled for x86.
Maybe some pre-define is fooling it.
Any ideas Evan?
