### ISSUE TITLE
Downstream porting documentation

### ISSUE THREAD

**Issue by bastien-roucaries** [simd-everywhere/simde#966]
Hi,

It is not really a bug but you get a mention on the debian wiki as one the easiest way to port sse instrinsic program
See https://wiki.debian.org/InstructionSelection

You will therefore get a few more testing and maybe bug report

Bastien (rouca@debian.org)

**Comment by mr-c** [comment]
Thanks @bastien-roucaries , it is great to see increased use of SIMDe in Debian !

FYI: I'm a Debian Developer and the maintainer of the Debian package for libsimde-dev
