### ISSUE TITLE
fyi: wasm2c using simde for simd support

### ISSUE THREAD

**Issue by ngzhian** [simd-everywhere/simde#971]
Using issues as a poor-mans notification system:

https://github.com/WebAssembly/wabt/pull/2021

**Comment by mr-c** [comment]
Wonderful, thank you for letting us know!

**Comment by mr-c** [comment]
Can you add an entry at https://github.com/simd-everywhere/simde/wiki/Projects-Using-SIMDe ?

**Comment by ngzhian** [comment]
Done! https://github.com/simd-everywhere/simde/wiki/Projects-Using-SIMDe/_compare/357b60c052728f466ec232f06ce4cfcc8c4f47be...75d12a2aa990d35989e575cce2815de852fd0efc
