### ISSUE TITLE
simde_mm512_add_epi32 SVE implementation is inefficient

### ISSUE THREAD

**Issue by dslarm** [simd-everywhere/simde#980]
The SVE version in https://github.com/simd-everywhere/simde/blob/master/simde/x86/avx512/add.h 
(#if defined(SIMDE_ARM_SVE_NATIVE) .. )
will cause many more instructions to be generated on any SVE implementation with <= 256 bits than a simple Neon implementation.

The number of instructions incurred for loop control in a vector-length agnostic SVE version is considerable on such a small loop body: the default Neon path will be 12 instructions - whereas the SVE implementation yields ~14 instructions on (eg) AWS Graviton3 (256b vectors), or ~28 instructions on 128b implementations. 

Furthermore, Neoverse V1 cores can execute either 4 neons instructions or 2x256b SVE per cycle - so the ordinary Neon implementation should also involve considerably fewer cycles than the difference in instruction count alone suggests.

**Comment by mr-c** [comment]
Thank you @dslarm for your report. Can you suggest an alternative implementation?

**Comment by dslarm** [comment]
The current implementation in Neon would be better for <= 512b - so I would swap the order of the two ifdefs:
`  #if defined(SIMDE_ARM_SVE_NATIVE)
      ..
    #elif SIMDE_NATURAL_VECTOR_SIZE_LE(256)`  

There are vector-length specific SVE implementations that would be fewer instructions for 256b, but given the 2x256 vs 4-pipe 128b vs 2-pipe 256b capabilities, in terms of cycles, the Neon would be fewer.

**Comment by dslarm** [comment]
@mr-c on second thoughts - it's likely that natural vector size isn't / wouldn't be set, and yet SVE is defined. I'll run a few checks and confirm.

**Comment by dslarm** [comment]
@mr-c - it seems that in all circumstances, at present SIMDe has SIMDE_NATURAL_VECTOR_SIZE of 128 for SVE platforms, regardless of the actual core implementation size. I don't know if that is by intention/design: allowing easier intermixing of Neon and SVE and always using length agnostic constructs in all SVE usage - but I think that would make sense.

Swapping that ifdef around would cause all SVE / non-SVE Arm platforms to use the original Neon implementations.  

I can't see a safe way to capture vector-size at compile time. There is one flag (-msve-vector-bits - which sets  __ARM_FEATURE_SVE_BITS to the value) but this generates vector-length specific binaries that **would not work correctly** if run on a machine with different SVE width than that set value. If SIMDe chose to do that (and risk) - then you could keep the order of the two ifdef checks, and replace with checking for ifdef of __ARM_FEATURE_SVE_BITS and  __ARM_FEATURE_SVE_BITS >= 512.  The compiler could also optimize that block heavily, in the knowledge that it is allowed to be vector-length specific.

Alternatively, given the weak benefit from SVE (512b only wins) in this case, it may be better to remove the SVE block.

**Comment by mr-c** [comment]
Thanks for looking into this @dslarm ; I'm not an expert at SVE or Arm.

Here is the original commit for SVE, the commit message may be helpful: https://github.com/simd-everywhere/simde/commit/f8f838253ac8a61e4c926a6276db78a2e4c36627
