### ISSUE TITLE
Number of arguments to _mm_clflush()

### ISSUE THREAD

**Issue by thomasdwu** [simd-everywhere/simde#990]
The Intel documentation for _mm_clflush() says it should have only one parameter:

https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#text=_mm_clflush&ig_expand=823

but the entry for _mm_clflush() in the file sse2.h says it should have two parameters, and it ignores both of them, although simde_mm_clflush does take one parameter and uses it.  I believe the fix is to make line 1356 read as

  #define _mm_clflush(p) simde_mm_clflush(p)

**Comment by mr-c** [comment]
@thomasdwu Good catch; can you send a PR with that fix? Thanks!

**Comment by thomasdwu** [comment]
I'm sorry, but I don't know what a PR is.  Otherwise, I would be happy to
help.  Thanks for all of your work on SIMD everywhere, which I am using in
a software package for the bioinformatics community.

Regards,

Thomas Wu

**Comment by thomasdwu** [comment]
Okay, I figured out what a pull request is and learned how to do one, so I
just did my first pull request on Github for this fix.  Please let me know
if anything is amiss.

Thanks,

Thomas Wu

**Comment by mr-c** [comment]
fixed in https://github.com/simd-everywhere/simde/commit/d46f0e7b89b036712cff2c4b516798a42ba74fd3
